### ISSUE TITLE
API returning "no results" for get_cases in example: "jhu-cases", "confirmed_incidence", 20200411-20200417

### ISSUE THREAD

**Issue by bbrewington** [cmu-delphi/covidcast#1]
When I tried to re-run this, it threw an error - because the API itself is returning no results

![image](https://user-images.githubusercontent.com/10573749/81342621-85e85c00-9081-11ea-95e4-e12d1bca71cd.png)

I believe this is the API call it's trying to do:

https://delphi.cmu.edu/epidata/api.php?source=covidcast&data_source=jhu-cases&signal=confirmed_incidence&time_type=day&geo_type=county&time_values=20200411-20200417&geo_value=%2A

API call results as of 2020-05-07 16:42 (Eastern):

`{"result":-2,"message":"no results"}`

Here's permalink to line of code in question:
https://github.com/cmu-delphi/covidcast/blob/c58e240ee078018f94ec6795a23ebf77afabed75/R-notebooks/signal_correlations.Rmd#L47

**Comment by ryantibs** [comment]
Thanks, it's been fixed now. (We had renamed the JHU data source and its signals.)
