### ISSUE TITLE
not hard-coding covidhub_probs

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#100]
Currently, the function `check_valid_forecaster_output` (in [evaluate.R](https://github.com/cmu-delphi/covidcast/blob/evalcast/R-packages/evalcast/R/evaluate.R)) makes sure that the forecaster has outputted all 23 quantile levels, hard-coded as `covidhub_probs`:

`covidhub_probs <- c(0.01, 0.025, seq(0.05, 0.95, by = 0.05), 0.975, 0.99)`

However, this is overly restrictive since, as Vishnu pointed out, [the COVID Hub submission instructions](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md) specify that for the task of "N wk ahead inc case", only 6 quantile levels need to be submitted.

Some options:

* simplest approach: remove this check or make it a warning rather than an error
* enforce (based on the forecasting task) one of these two COVID Hub sets of probs
* don't enforce any particular choice but make sure the set of quantile levels reported is consistent across all locations and aheads for a forecaster?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970447730609) by [Unito](https://www.unito.io/learn-more)

**Comment by dajmcdon** [comment]
I'm attempting to go with option (c) "don't enforce any particular choice but make sure the set of quantile levels reported is consistent across all locations"
