### ISSUE TITLE
Address R CMD CHECK notes

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#105]

**Comment by bnaras** [comment]
I'll take this.

**Comment by dajmcdon** [comment]
We're running into this with the `aardvark` refactor, `strawman`, even the `template` package. I'm assuming its the same issue. Ignoring at the moment, but there's [this note](https://dplyr.tidyverse.org/articles/programming.html#eliminating-r-cmd-check-notes) from `dpylr`, if you haven't seen it. Seems like a pain to

**Comment by jacobbien** [comment]
Thanks @bnaras.  Inspired by what Naras had done in evalforecast, I wrote a bit of code that is commented out in [globals.R](https://github.com/cmu-delphi/covidcast/blob/evalcast/R-packages/evalcast/R/globals.R) to process the output of R CMD CHECK...

```
txt %>%
   str_extract_all("global variable ‘[a-z_0-9]+’") %>%
   unlist() %>%
   paste(collapse = ",\n") %>%
   str_replace_all("global variable ‘|’", "\"") %>%
   unique() %>%
   cat()
```

**Comment by bnaras** [comment]
@jacobbien and @dajmcdon: The use of `utils::globalVariables()`, though a recommended solution, was always a bit hacky. I had to do that for `evalforecast` and other packages initially for expediency. The solution now is to use either the embrace operator `{{ }}` or `rlang::.data` to get around these notes.  I started doing this for `baseline_forecaster` and also for the simpler `absolute_error()` in `err_measures.R`. These are on the https://github.com/bnaras/covidcast/tree/evalcast_naras_issues. You can check this version (which has the call to `utils::globalVariables()` commented out)  and you will see that no notes will appear for the baseline forecaster and the absolute error function. 

However, before I go too far down this path, it is important to have some tests/examples to ensure that nothing breaks.

**Comment by bnaras** [comment]
I am now done with this and have made a PR.
