### ISSUE TITLE
Allow a forecaster to have additional arguments

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#106]
A primary use case would be when a forecaster uses a static data frame (e.g., census data).

- `get_predictions` would be passed these additional arguments using ...
- Perhaps `baseline_forecaster` should be modified to demonstrate this functionality?  Or at least its documentation could be
- these additional arguments would then be passed to forecasters

**Comment by ryantibs** [comment]
@bnaras @brookslogan I happen to have implemented this on a branch (since I needed it for another purpose) ... hopefully you guys haven't sunk time into this.  I will submit my branch as a PR probably tonight or tomorrow.

**Comment by jacobbien** [comment]
Implemented in #146.
