### ISSUE TITLE
Update covidcast.metadata() return values in docstring

### ISSUE THREAD

**Issue by chinandrew** [cmu-delphi/covidcast#109]
Currently the docstring is missing a few columns which get returned, and is also out of order

documented:
` data_source signal min_time max_time geo_type time_type num_locations min_value max_value mean_value stdev_value`

returned (with example row:

```
        data_source                 signal time_type geo_type   min_time   max_time  num_locations  min_value  max_value  mean_value  stdev_value  last_update  max_issue  min_lag  max_lag
0     doctor-visits       smoothed_adj_cli       day   county 2020-02-01 2020-10-01           2514    0.00000  87.670832    2.674555     3.358741   1601853923   20201004        2      129
```

capnrefsmmat  I'm not actually sure what those last 4 undocumented columns mean, is there a reference somewhere? Is the last updated in unix time, and if so, is that intentional? (1601853923 = Oct 4)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970309905194) by [Unito](https://www.unito.io/learn-more)

**Comment by chinandrew** [comment]
I think I found the answers [here](https://github.com/cmu-delphi/delphi-epidata/blob/d3a412c9b69c8e2e5e25340993ac5159a69a01b0/docs/api/covidcast_meta.md)

Should we convert the unix time to a date[time] object?

**Comment by capnrefsmmat** [comment]
Yeah, I think that'd be helpful. It's unfortunate that a Unix timestamp crept into the metadata, so let's convert it to a datetime.

**Comment by chinandrew** [comment]
:+1: Done in #118
