### ISSUE TITLE
plot_coverage - implement type = "one"

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#119]
The function [`evalcast::plot_coverage`](https://github.com/cmu-delphi/covidcast/blob/evalcast/R-packages/evalcast/R/plot_calibration.R) has an option `type = "one"` which is not yet implemented.

This would be a line plot of prop_covered vs. forecast_date, where prop_covered is the proportion of locations for which the nominal 100(1 - alpha)% interval covers the actual value.  Each forecaster would be a colored line.

**Comment by ryantibs** [comment]
@jacobbien In my pass over evalcast's plotting functionality, I just implemented this one.  PR coming soon.

**Comment by jacobbien** [comment]
Great!

**Comment by jacobbien** [comment]
Implemented in #146.
