### ISSUE TITLE
Vignettes for evalcast

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#120]
[These slides](https://cmu-delphi.github.io/covidcast/talks/evalcast/talk.html) demonstrate state-level incidence forecasting.  However, we should also have short vignettes demonstrating

* state-level cumulative forecasting
* US-level forecasting
* county-level forecasting (perhaps with cases to match what is available on COVID Hub)

Note: for k-week-ahead cumulative forecasting, one would set `incidence_period = "day"`, use the covidcast signal that is a cumulative signal, and take `ahead = k * 7`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970442142218) by [Unito](https://www.unito.io/learn-more)

**Comment by JedGrabman** [comment]
I'm starting work on a vignette. Can you assign the issue to me?

My initial plans

**Getting predictions**:
* Using `get_predictions` (with `baseline_forecaster`)
* Using `get_covidhub_predictions` (with "CMU-TimeSeries")
  * May make use of `get_forecast_dates` and `filter_predictions`

**Evaluating predictions**:
* `evaluate_predictions`
* plots
  * `plot_coverage`
  * `plot_width`
  * `plot_measure`

I can start with one of the cases in the first post and then decide how detailed we want the other cases to be. How does that sound?

**Comment by jacobbien** [comment]
Thanks, Jed this sounds great!

**Comment by dajmcdon** [comment]
Closed by #155
