### ISSUE TITLE
fix plot_width to depend on cards

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#129]
Currently the function `evalcast::plot_width` takes in an argument called `cards` but then uses `scorecards`.  Very wrong, but easy to fix.

**Comment by ryantibs** [comment]
@jacobbien I spotted this in my review of evalcast, and fixed it my 2nd commit on the evalcast-update branch that will be forthcoming!

**Comment by jacobbien** [comment]
Fixed in #146.
