### ISSUE TITLE
Find or produce county and state data files for the Python package

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#13]
The R package has some convenience data included to look up counties, MSAs, etc., and includes polygons to map some of them. Even if the Python package doesn't include mapping features, we should find a good source of similar data. 

If there's an existing Python package that includes the data and polygons we want, we could just include a couple examples showing how to use it. If there isn't, we can adapt `R-packages/data-raw/make.R` to produce the data files in a format the Python package can use easily.

**Comment by chinandrew** [comment]
Changed this ticket to state and county and made #38  for HRR and MSAs
