### ISSUE TITLE
Derivative functionality

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/covidcast#131]
Direction isn't being supported in the API anymore, and we decided to move all direction calculations over to the client side.

First, we should nix the references to direction in the R package entirely (and eliminate any functionality that uses it, like the plotting functionality).  I believe this was done for the Python package in #128.

We should offer functionality in the covidcast package(s) to compute _derivatives_ of signals, and then simple functionality to turn derivatives into _direction_ calls.  Here's my thoughts about how this should look.  This would be a fun issue to tackle because it's very concrete, and contains a nice mix of signal processing and design.  Tagging sgsmob dshemetov huisaddison chinandrew because they might be interested.  cc jsharpna capnrefsmmat krivard

At the outset, whether it should be done in both R and Python (or just R, and not Python): I'm not sure.  I'm going to write everything below in R notation but the main ideas should transfer of course to Python.

## Simple example
Let's start with a simple example, of what I would want to be able to do.  If I have a signal data frame `df`, then I should be able to call:

```
df_deriv = compute_deriv(df, method = "linear-reg", n = 14)
```

This would run, separately for each location in `df`, and each t = `time_value`, a linear regression of y = `value` on x = `time_value`, using last n = 14 days of training data (where x = t - 13, ... x = t).  It would then populate a new column called (say) `deriv` and append this to `df`, where the `deriv` column contains the fitted slope (the coefficient multiplying the dependent variable x in the regression).

## Available methods
For available methods, as specified through the `method` parameter, I would start by just allowing two: "linear-reg" (the default) for linear regression, and "smooth-spline" for a smoothing spline.  For the smoothing spline, the `deriv` column would be populate by the derivative of the fitted smoothing spline at x = t.  You can use [`smooth.spline()`](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/smooth.spline), and then evaluate its derivative via [`predict.smooth.spline()`](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/predict.smooth.spline).

Additional methods to consider for fun: if you implement trend filtering, we can celebrate with a cup of coffee or a glass of scotch.  If you implement wavelet smoothing, I will reject your PR.

## Other arguments
I would allow for the following arguments in `compute_deriv()`:

* `n`: the number of trailing days to use to train the model used to estimate the derivative. Default is (say) n = 14.
* `new_col`: the name of the column to store the derivative in. Default is `deriv`. Note: the user could specify `value` in order to overwrite the signal value with the derivative (which could be useful for plotting purposes: they could then just use the plotting functionality directly on the returned data frame).
* `params`: a list of optional parameters to pass to the method for estimating the derivative. Default is `params = list()`. For example, for a smoothing spline fit through `smooth.spline()`, you could specify in `params` the number of degrees of freedom, or whether to use cross-validation, and these arguments would get passed to `smooth.spline()`.

## Challenges
I can foresee missingness being a challenge. What do you do when there's missing data? Not enough data for training? All these corner cases are going to require care.

I wouldn't worry about computational efficiency at the start (although I would implement linear regression carefully, since it's just so simple here---analytically invert the 2 x 2 matrix in question! don't call a linear modeling routine!). But eventually we may have to start worrying about computational efficiency, depending on how fancy the methods get or how big the data sets get.

## Vignette
We should add an article to our [R vignette](https://cmu-delphi.github.io/covidcast/covidcastR/) with lots of nice examples spelling out how to use the derivative functionality.  The vignette should also show how to "hack" our plotting functionality to plot choropleth maps of derivatives.

## Direction rules 
I think we should hold off on discussing this until we have the derivatives working and have lots of examples.  Even then, I'm not sure we even need to offer built-in functionality to for direction calls from derivatives because it should be easy enough for a user to do directly, using (say) a function like [cut()](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/).  At the least, we can just add examples to the vignette showing how you might do this, and then again show how to "hack" our plotting functionality (and set a custom color scale) to plot a color map of direction values.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970303979537) by [Unito](https://www.unito.io/learn-more)

**Comment by dshemetov** [comment]
@ryantibs Re: handling missingness, when anticipating that issue in the smoother util, I settled on imputation using polynomial fits on the past data. The training data window on the boundaries was shrunk to accommodate smaller amounts of data. It seemed to work fine on the signals I tested. What do you think of such an approach?

**Comment by ryantibs** [comment]
@dshemetov Sure seems generally reasonable to me, but of course the details matter.  Whoever end up working on this derivative issue (if not you), you should share notes with them.  

You made me realize that I should note that derivative estimation as being discussed here is operating at a different level than smoothing: it's operating on signals that are coming out of the API (possibly even smoothed ones, because you can calculate a derivative on anything you want).  One might guess that you could do better if you had access to the raw data (you could simultaneously smooth and estimate a derivative, for example ... lots of methods allow you to do both simultaneously).  But for a variety of reasons it makes sense to put derivative estimation on the client side, so access to raw data's out of the question.

**Comment by dshemetov** [comment]
@ryantibs noted. Hopefully the worst smoothing will do is have an attenuating effect on the derivative. 

How do you envision turning derivatives into direction calls? What other downstream uses do you anticipate of this method?

**Comment by chinandrew** [comment]
> @ryantibs noted. Hopefully the worst smoothing will do is have an attenuating effect on the derivative.
> 
> How do you envision turning derivatives into direction calls? What other downstream uses do you anticipate of the derivative method?

Previous direction implementation was: `-1 for decreasing, 1 for increasing, and 0 for neither`, and github archaeology reveals this https://github.com/cmu-delphi/delphi-epidata/blob/06e3851adaca1ad3746ac36c76e4ee2bf42acf42/src/acquisition/covidcast/direction.py, though someone else can confirm if this is the most recent

**Comment by krivard** [comment]
Additional details: git issue [Revise definition of "historical variability" in direction/trend calculations](https://github.com/cmu-delphi/covidcast-indicators/issues/224)

**Comment by huisaddison** [comment]
I would be happy to pick this issue up (not sure how to assign myself - when I click on "No one assigned" under assignees, nothing comes up...)

As I mentioned during today's meeting, I'd feel bad if I "stole" this issue from somebody interested in working on it, so @dshemetov definitely don't feel bad if you decide you do want to work on it.  I probably won't start working on this in earnest sometime next week, so I'll ping you beforehand to make sure :)

**Comment by ryantibs** [comment]
Thanks Addison!  I assigned both @huisaddison @dshemetov just in case Dmitry wants to work on it as well.  

Just wanted to note that I already "struck direction from the record" on my multi-signals branched, see PR in #156.  (It now appears nowhere in the covidcast package, so that part is already done.)

I may also, very soon, implement the linear regression derivative estimator on my modeltools branch I'm working on now.  I need it for something else that I'm working on now.  If I do this I'll make sure to point you guys to it.

**Comment by ryantibs** [comment]
Hi folks, particularly @huisaddison @dshemetov, my PR here: #334 should close this issue.  I didn't think anybody was actually working on this (hope I wasn't wrong about that?), so I went ahead and implemented it along with similar functionality (for a new package call modeltools that's under development). 

That said, I'd be very happy for @huisaddison @dshemetov to take a look at how it's implemented and leave feedback (there's a vignette on the "modeltools" branch that demos how it works).

**Comment by huisaddison** [comment]
Thanks for following up Ryan -- I hadn't been working on this.  I'll play with your `modeltools` implementation tomorrow and leave some feedback (if anything behaves unexpectedly).

**Comment by ryantibs** [comment]
Thanks @huisaddison.  Just a comment on the style of implementation I ended up choosing: I went for generality, rather than pure speed.  If restricted more, I think it could be further optimized, but I ended up wanting to allow for a bit more flexibility.
