### ISSUE TITLE
Allow for a non-quantile forecast in a predictions card

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#132]
A predictions card has two columns: `probs` and `quantiles` (see e.g. [this slide](https://cmu-delphi.github.io/covidcast/talks/evalcast/talk.html#(7))).  However, sometimes a forecaster may produce a point forecast.  (For example, on the COVID Hub they allow forecasters to submit point forecasts in addition to quantile forecasts.). This could be useful for hotspot detection where one might simply want to predict a 1 or a 0.

To accommodate this, I would suggest that we allow predictions cards to have a row where `probs` is `NA`.  For point forecasters (including hotspot detection), the predictions card could simply be a 1-by-2 tibble with `NA` in the `probs` column and the value of the point forecast in the `quantiles` column.  More generally, one could allow a quantile forecaster to also have an additional row with a point forecast.

The reason to code this as an `NA` would be so that the `probs` column would remain numeric.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970302781344) by [Unito](https://www.unito.io/learn-more)

**Comment by nickreich** [comment]
Wondering if you all have looked in detail at the data structure at zoltardata.com that hosts the Hub forecasts and whether (a) you could download data from the API from there directly via our R or python package or (b) you could design your system to more directly interface with these general forecast data types?

**Comment by jacobbien** [comment]
Thanks Nick.  In issue #99 I had made a note that we should be using zoltr rather than scraping -- definitely the better thing to do!  In terms of accommodating more general forecast data types, this is not something I had considered.  I was able to find [this page](https://docs.zoltardata.com/targets/).  I assume this is what you are referring to?

**Comment by nickreich** [comment]
Yes that is the right reference point. Probably overkill to engineer evalcast to deal with anything other than quantile/point forecasts (although CDC has used bin forecasts in the past as well), but just wanted to make sure that this general conceptual  framework for forecasts was on your radar as you move forward with design.
