### ISSUE TITLE
Make covidcast.signal give more specific warnings when data is not available

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#139]
See https://github.com/cmu-delphi/covidcast-indicators/pull/343#discussion_r510188822

We should augment the warnings with source, signal, date, and geo_type, so anyone logging can find this out. (We already did this in the R package by raising a custom warning condition that can be handled appropriately with a logger.)

**Comment by chinandrew** [comment]
You're referring to this message in the R package right? 

```
Warning message:
Fetching smoothed_cli from fb-survey for 20201022 in geography '*': no results
```

**Comment by capnrefsmmat** [comment]
Yes -- it raises a custom warning object with all the additional information attached: https://github.com/cmu-delphi/covidcast/blob/02fc4dfc3b40587a2102166fef25255bfe60af4e/R-packages/covidcast/R/covidcast.R#L660

R's condition system lets users intercept that warning and log it however they desire.

**Comment by chinandrew** [comment]
So spend a bit of time looking into this, it seems like Python doesn't really emphasize adding custom attributes to warnings over just passing a message through. You _can_, but not sure it's generally used. This was based on 30 min of googling so maybe there's something I'm missing.

For now, I'm thinking of adding a custom warning class called `NoDataWarning` and having it warn with a message like 
```
f"No {data_source} {signal} data found on {cur_day} for geography '{geo_type}'"
```

Thoughts?

**Comment by capnrefsmmat** [comment]
Yeah, that sounds fine. I agree that custom warning attributes aren't common in Python, so ensuring the message is descriptive is probably the best thing.

(Custom warnings actually aren't used much in R either, which is a shame, because R's error-handling system is actually cloned from Common Lisp's condition system. It's fantastically sophisticated and flexible, and nobody uses it.)
