### ISSUE TITLE
Set up branch protection and code owners in this repo

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#141]
GitHub supports branch protection, preventing people from pushing to `main` without code review. It also supports [code owners](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners), which would let us specify that certain people have to review changes to certain sets of files.

For example, we could designate two or three R package maintainers and require their review on changes that touch the R package, while having separate maintainers for the Python package.

This would ensure we don't push anything directly to `main` without checking with someone who knows if the change will break something. More important now that we have more users and more packages in this repo.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970430367823) by [Unito](https://www.unito.io/learn-more)

**Comment by capnrefsmmat** [comment]
I propose the following code ownership setup:

* `R-packages/covidcast/`: @capnrefsmmat, @ryantibs, + 1 new maintainer (will @JedGrabman be handling the R package long-term?)
* `R-packages/evalcast/`: @jacobbien plus -- who else will be maintainer here?
* `Python-packages/covidcast-py/`: @capnrefsmmat, @chinandrew (+ @krivard if she wants)
* `R-notebooks/`: @ryantibs?

Suggestions for improvements to this roster?

**Comment by krivard** [comment]
Do we want to keep the dashboards in this repository, or move them to `data-integrity`? cc @benjaminysmith

**Comment by benjaminysmith** [comment]
I think we should leave the dashboards here for now since they also serve as public demonstrations of the API.

**Comment by krivard** [comment]
Fixed in #261
