### ISSUE TITLE
evalcast, caching, s3 method

### ISSUE THREAD

**Issue by bnaras** [cmu-delphi/covidcast#150]
jacobbien dajmcdon It seems to me that caching should always be available for the user to control. So any function we provide that can cache should take a boolean flag as argument (maybe default TRUE) along with a `cache_path`, which, if null, reverts to memory cache. This is because if such a function is being run in a production system at a time that straddles the instant when new covidcast data becomes available, making caching the default will ensure that the stale data remains in that session, silently. The user should have control.

If I am not mistaken, in `baseline_forecaster()` the use of `download_signal()` seems to do some computations to get the `location` variable. While we can use such a function internally, I don't think `baseline_forecaster()` (which I am thinking of as a template for other forecasters users might write) should hide it. If a common task, this functionality can directly provided in an exported function in covidcast.  Then, a vignette can clearly explain how to use those covidcast functions directly to produce the df that is the first arg to `baseline_forecaster()`.

As I am adding S3 plots methods, etc., I am not getting a sense of what is gained by it. Taking `lm()` as an example, there is a very obvious concept of the model object, its behavior, methods etc.  I can't seem to figure out an analogous reason to elevate prediction_cards to an object, other than the fact that they can be plotted and printed. They are tibbles after all, and tidyverse provides ways to slice and dice them any which way. I might be missing something, so please let me know.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970432225928) by [Unito](https://www.unito.io/learn-more)

**Comment by dajmcdon** [comment]
I don't have a problem with forcing caching to be under user control, but it is a much more "quiet" fix to do it this way. It does lose flexibility though. The cache would be more readable if we did it differently. I think there are multiple ways to do this depending on how much control do we want to give the user. We could turn it off by default and give a message at load with a line of code to run. That would allow selecting between memory and disk. But via `memoise`, it's hard to access the cache for the user. Passing the argument through everywhere would allow more control of the name of the stored objects, but maybe be more painful to use.

**Comment by dajmcdon** [comment]
As for the S3 methods, I agree. Especially with the prediction cards. And I'm finding some issues with score cards too. For prediction cards, better might be a way to collect arbitrary numbers of cards (multiple aheads, forecasters, as_ofs, forecast_dates) and just write them to a long dataframe (without the embedded tibbles). I think there are lots of plots the user _might_ want to make, and if we make a plot method that only works under some conditions, it may be confusing. Score cards suffer this too to some extent (examining multiple aheads seems to break the wedge_plot for example), but there seem to be more calculations necessary to get the right information than with prediction cards.

**Comment by dajmcdon** [comment]
Oh, and while I'm still thinking about caching, I think we probably want to cache the covidhub predictions too. Or add them to our API? Downloading a bunch of csv's and then filtering can get slow.

**Comment by jacobbien** [comment]
I'm responding to the S3 aspect of this discussion in issue #98 just to keep things organized.

**Comment by jacobbien** [comment]
@dajmcdon - regarding your last bit about the covidhub predictions, if we integrate with the zoltr package as discussed in #99 then having them in our API does not seem necessary.  Right?
