### ISSUE TITLE
Use consistent data types for dates in evalcast

### ISSUE THREAD

**Issue by JedGrabman** [cmu-delphi/covidcast#153]
Evalcast is inconsistent with its use of dates. In particular, get_forecast_dates returns character objects, but filter_predictions expects date objects and fails silently for character objects.

Underlying cause for this particular issue seems to be odd behavior by dates. 
`date("2020-07-20") == "2020-07-20"` is TRUE

`date("2020-07-20") %in% "2020-07-20"` is FALSE

Probably safest just to require dates everywhere.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970295119777) by [Unito](https://www.unito.io/learn-more)

**Comment by jacobbien** [comment]
Thanks @JedGrabman good point!
