### ISSUE TITLE
Minor improvements for evalcast trajectory plots

### ISSUE THREAD

**Issue by jsharpna** [cmu-delphi/covidcast#160]
- [x] add pagination for when number of locations exceed threshold
- [x] tune the size of trajectory plots
- [ ] tune the font size

(If you have access) you can see what I did for the [QA plots here](https://github.com/cmu-delphi/covidcast-forecast/blob/main/forecaster_predictions/submit_predictions/code/trajectories.R), basically I just used `facet_wrap_paginate`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970294899032) by [Unito](https://www.unito.io/learn-more)

**Comment by jsharpna** [comment]
want to assign to @yelselmiao

**Comment by dajmcdon** [comment]
Closed with #213 and #247
