### ISSUE TITLE
fb_dashboard fails to generate

### ISSUE THREAD

**Issue by benjaminysmith** [cmu-delphi/covidcast#211]
Output from RScript is: 

Rendering fb_dashboard ... Problem with `filter()` input `..1`.
✖ object 'value' not found

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198973301734245) by [Unito](https://www.unito.io/learn-more)

**Comment by benjaminysmith** [comment]
(I'll investigate this but looks like I don't have permission to assign to myself)

**Comment by chinandrew** [comment]
assigned

**Comment by krivard** [comment]
interesting; looks like the last time my cronjob successfully generated the facebook dash was 4AM on Oct 13.

**Comment by benjaminysmith** [comment]
Even weirder -- as of this morning I can no longer reproduce the problem.

I suspect this might have been related to the JHU issue -- that signal is used for generating the correlations.
