### ISSUE TITLE
Aggregate cards into a tibble

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#221]
Create a function `aggregate_cards()`.

- [x] Should appropriately handle prediction cards or evaluation cards
- [x] Should also accommodate lists of these, for instance the output from `get_predictions()` run twice with different arguments.
- [ ] Ensure that this function is used throughout `evalcast` (eg in `plot_trajectory()`)

See also #98

**Comment by sgsmob** [comment]
I'm reading back through the previous discussions and I am not clear on the input/output types here.

On the input side am I correct that we should expect:
* A list of 2-column data frames with columns:
    * Geo code
    * 23 by 2 tibble with columns:
        * Quantile
        * Predicted value (prediction cards) or error (evalutait
?

On the output side, should there be a single data frame in the same format as above such that the predicted values are averaged over all elements of the list?  The same thing but the predicted values are a list of the values (i.e., go from a list of frames to a frame of lists)?  Something completely different?

**Comment by dajmcdon** [comment]
Something a bit different. Basically the geo code should be repeated for every one of the 23 quantile/value pairs. One also needs the many of the attributes of the card. If you look from [here](https://github.com/cmu-delphi/covidcast/blob/9c5848152b966fb97cff666059ee8574e07b16e9/R-packages/evalcast/R/plot_trajectory.R#L34) until about line 48, that should be most of it. It may also help to see the [notebook](https://htmlpreview.github.io/?https://github.com/cmu-delphi/covidcast/blob/covidhub-eval/R-notebooks/covidhub_evaluation.html) Ryan posted this morning. He basically did it manually there.

**Comment by sgsmob** [comment]
So the output is a single tibble with columns:

- Geo code
- Forecaster name
- Number of weeks ahead
- Quantile
- Predicted value or error

and there is a 1:1 correspondence between each row in the output and a row in one of the cards in the list?

**Comment by dajmcdon** [comment]
that's right. Produce 1 tibble. But you will also, need some other things. If you look at line 162 of `get_predictions.R`, all the attributes are listed there. I don't think we need `forecaster` or `corrections_applied` since they are functions. Probably not `forecaster_params` either (maybe make that an option to the function). On the `score_cards` you need much of the same plus some of the other things. 

Imagine I run 2 forecasters each at 3 aheads on 5 different forecast dates. I want to put everything in one tibble that contains any information I would want to try to summarize or plot the output. Same for the score cards.
