### ISSUE TITLE
Print methods for cards

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#222]
See @jacobbien 's discussion in #98.

Not clear if we want full S3 classes for pcards and ecards (see #150).

Minimum deliverables required:
- [ ] Both types of cards should have a print method to avoid the problem mentioned in #98 

Complete solution:
- [ ] Do we actually give these a class? 
- [ ] Perhaps the class only propagates to print and `aggregate_cards()` (#221 )
- [ ] Probably do not want plot methods for these (aggregating and then just passing to ggplot gives more freedom).
- [ ] How do we handle 1 set of cards versus a list of cards?

**Comment by sgsmob** [comment]
Essentially should print out a formatted `all_attr`.
