### ISSUE TITLE
Fail gracefully

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#224]
From @ryantibs:

>  if anything goes wrong in evaluating predictions, at any of the forecast dates or any of the aheads, for example, then it quits (via an `assert_that()` statement).  I think we need to go through all the `assert_that()` statements and ask---is this really needed, or can we issue a warning, return an `NA` from that function, and rewrite the parent functions to proceed gracefully? 

- [x] Ensure that these sorts of errors/warnings happen only when necessarry.

**Comment by ryantibs** [comment]
To be clear, I meant that this should be true overall, across the whole evalcast package, and not just within `evaluate_predictions()`.

**Comment by bnaras** [comment]
I agree that `assert_that()` should catch errors, not warnings or situations where an `NA` return would make sense.
