### ISSUE TITLE
Hardcoding

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#227]
Locate "signals" or other instances of hardcoded values. Either remove or flag for later evaluation

**Comment by sgsmob** [comment]
I don't really understand what this means.  What values are we concerned about being hardcoded?   A quick grep through evalcast for `signals` doesn't identify anything I would consider "hardcoding".

**Comment by dajmcdon** [comment]
I know that there's a vector of probabilities explicitly spelled out somewhere. Any references to "jhu-csse" or the like should go (that's what I meant by "signals"). Actually, I need to make a pass through everything to try to make it all readable. So I'll do this at the same time. I'm going to unassign both of you.
