### ISSUE TITLE
Allow `trajectory_plots()` to display more quantiles

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#230]
For a nice example of the desired behavior, see https://covid19forecasthub.org/talks/zoltar.html#(11)

**Comment by kateharwood** [comment]
Is this one of the issues you were hoping to prioritize?

Which slide in particular on the zoltar deck shows the example? (Slightly confused on what exactly this issue is)

**Comment by dajmcdon** [comment]
For the moment, I was leaving this as "lower priority" since it isn't key to either our pipeline or anything anyone is working on (that I know of). I was thinking Slide 11. I'll fix the link above.
