### ISSUE TITLE
covidcast::covidcast_signal - substantial speed improvement possible

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#231]
The function `covidcast_signal` queries the API one day at a time.  I believe this behavior dates back to an original version of this function I wrote (before the package existed) in which I was focused on downloading county-level data.  The API caps the number of values it can return to a number in the 3000s, so for county-level downloads it made sense to break queries by date.

However, when we're downloading state-level data, things could be much faster if we don't do it this way.  Here is an example to demonstrate:

```
library(covidcast)
library(lubridate)

start_day <- ymd("2020-06-01")
end_day <- ymd("2020-08-01")
as_of <- ymd("2020-10-31")

system.time({
  sig1 <- covidcast_signal(
    data_source = "jhu-csse",
    signal = "deaths_incidence_num",
    start_day = start_day,
    end_day = end_day,
    geo_type = "state",
    as_of = as_of
  )
})
# user  system elapsed 
# 0.832   0.038   7.100 

days <- seq(start_day, end_day, by = 1)
length(days) * 52 # num requests is 3224, below the API limit

system.time({
  sig2 <- covidcast:::covidcast(
    data_source = "jhu-csse",
    signal = "deaths_incidence_num",
    time_type = "day",
    geo_type = "state",
    time_values = covidcast:::date_to_string(days),
    geo_value = "*",
    as_of = as_of,
    issues = NULL,
    lag = NULL
  )
})
# user  system elapsed 
# 0.063   0.004   1.901 

range(sig2$epidata$value - sig1$value) # identical output
```

My suggestion would be to have `covidcast_signal` figure out how many queries there would be and then break this up into the fewest requests to the API possible.

**Comment by jacobbien** [comment]
Here's another example in which we only want the data for a single location:

```
start_day <- ymd("2020-04-01")
end_day <- ymd("2020-10-01")
days <- seq(start_day, end_day, by = 1)

system.time({
  sig3 <- covidcast_signal(
    data_source = "jhu-csse",
    signal = "deaths_incidence_num",
    start_day = start_day,
    end_day = end_day,
    geo_type = "state",
    geo_values = "ca",
    as_of = as_of
  )
})
# user  system elapsed 
# 2.50    0.11   19.92 

system.time({
  sig4 <- covidcast:::covidcast(
    data_source = "jhu-csse",
    signal = "deaths_incidence_num",
    time_type = "day",
    geo_type = "state",
    time_values = covidcast:::date_to_string(days),
    geo_value = "ca",
    as_of = as_of,
    issues = NULL,
    lag = NULL
  )
})
# user  system elapsed 
# 0.013   0.000   0.203 

range(sig4$epidata$value - sig3$value) # identical output
```

**Comment by ryantibs** [comment]
Great point.  I hadn't even realized we weren't taking advantage of the fact that you can pass the API a list of dates.  

Seems like a good thing for @JedGrabman to look into, if he has cycles.  He has already worked on the complementary angle of allowing multiple geo values angle in #151.

**Comment by ryantibs** [comment]
Also, we may want to check in with the engineering side, maybe see if @undefx knows, to see if there's going to be built-in support on the API side to support more than 3000 queries (is that called pagination)?

**Comment by capnrefsmmat** [comment]
Pagination has been requested before, but I don't think it's on the near-term engineering roadmap: https://github.com/cmu-delphi/delphi-epidata/issues/51

I considered having the package try to be smarter about batching queries for geo_types other than county, but initially decided against it on the grounds that it's excess complication (the package would need to know how many HRRs, MSAs, DMAs, and states there rae, to calculate correctly) that would be removed once pagination is supported. But if pagination is a long way off, it may be worthwhile.

**Comment by JedGrabman** [comment]
I'm working on checking for known geo_values in the validator, so I can reuse some of the data generated there. It sounds like for the moment, we will assume that we can handle up to 3000 rows per request. I think it won't be too bad to handle the different types (HRRs, etc). As long as we can come up with reasonable upper bounds for those values (which I think we can since it seems like we have the same amount of data each day), we can just set some constants. I presume we have an identifiable error if we request too many rows, if we do we can check for it and fall back on single day processing as a backup if the original process fails in some way.

I'm a little backlogged, but I think some other issues can wait, since it seems more important.

**Comment by ryantibs** [comment]
Thanks Jed.  Appreciate it!  If you want help prioritizing (or re-prioritizing) happy to go over what you're working on in my OHs.

**Comment by JedGrabman** [comment]
Developing over at [JedGrabman/covidcast:dev-covidcast-efficiency](https://github.com/JedGrabman/covidcast/tree/dev-covidcast-efficiency). Need to do some cleanup and add tests, but results are promising

```
# All States
system.time({
  for (i in 1:10){
     ...
  }
})
# user  system elapsed 
# 1.78    0.00   15.72 

...

system.time({
  for (i in 1:10){
     ...
  }
})
# user  system elapsed 
# 0.89    0.02   12.75 
```
3.7x -> 1.2x

```
# Just CA
system.time({
  for (i in 1:10){
     ...
  }
})
# user  system elapsed 
# 0.76    0.00    3.94 

system.time({
  for (i in 1:10){
     ...
    )
  }
})
# user  system elapsed 
# 0.14    0.00    1.28 

range(sig4$epidata$value - sig3$value) # identical output
```
100x -> 3x

Example updated messages (from runs with different inputs):
`Fetched day 2020-04-01 to 2020-10-01: 1, success, num_entries = 184`  
`Data not fetched for some geographies on 2020-10-30: 06111, 04019 `
`Data not fetched for the following days: 2020-10-31 `

**Comment by ryantibs** [comment]
@jacobbien @JedGrabman Are we good to close this issue?  Looks like Jed's #275 takes care of it?

**Comment by jacobbien** [comment]
Nicely done @JedGrabman!  This is a huge speed improvement.

Now I did try rerunning my examples to see how long they take now.  When I run [this example](https://github.com/cmu-delphi/covidcast/issues/231#issuecomment-719987420), the elapsed time is down from the 19.92 seconds to 2.277 seconds, which is wonderful.  However, recall that in that above comment I was able to get an elapsed time of 0.265 seconds by calling `covidcast:::covidcast` directly to produce the identical output.  Do you know why there's still this somewhat large difference in run time?

**Comment by capnrefsmmat** [comment]
It looks like the new code doesn't take into account the `geo_value` argument -- it batches the queries as if you were requesting all states, not just the one state. I think that'd just be a simple fix to use the number of `geo_values` provided, if any, and use the total number of locations otherwise.

**Comment by jacobbien** [comment]
Good point @capnrefsmmat!

**Comment by JedGrabman** [comment]
Sounds right. Should be as simple as a basic check and updating the `max_geos` param [here](https://github.com/cmu-delphi/covidcast/blob/dabc78fc508ec60c2d0549bcc8e82bed1d005b34/R-packages/covidcast/R/covidcast.R#L260).

**Comment by capnrefsmmat** [comment]
Closing; this is done in #275 and follow-ups.
