### ISSUE TITLE
Add Puerto Rico to R plots

### ISSUE THREAD

**Issue by chinandrew** [cmu-delphi/covidcast#24]
Currently Puerto Rico is not plotted even if a signal exists for that region.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970318890831) by [Unito](https://www.unito.io/learn-more)

**Comment by ryantibs** [comment]
@JedGrabman @sarah-colq This seems like another good one for Sarah to try (as she's learning R).  Maybe Sarah you could give it a shot and Jed could give you feedback/guidance?  

And don't hesitate to check in with @chinandrew (or directly check out what he did in #18 for Puerto Rico in the Python package) to see whether this was done by Puerto Rico's exact lat/lon (I would guess not) or some kind of transformation (I would guess so).  Heck, while we're at it we might even corrupt Andrew a bit and get some R to rub off on him ...

**Comment by chinandrew** [comment]
> And don't hesitate to check in with @chinandrew (or directly check out what he did in #18 for Puerto Rico in the Python package) to see whether this was done by Puerto Rico's exact lat/lon (I would guess not) or some kind of transformation (I would guess so). 

In the Python package, Alaska, Hawaii, and Puerto Rico were all transformed to roughly match positions with the web map. 

> Heck, while we're at it we might even corrupt Andrew a bit and get some R to rub off on him ...

:imp:. Not opposed to this, though my R development speed will be an order of magnitude slower given I haven't used it in 3 years. Syncing with Katie later this week to align on responsibilities and will have a better idea of my time allocation afterwards

**Comment by sarah-colq** [comment]
I'm going to try this.  My R development knowledge is about a week old @chinandrew so I am right there with you.

**Comment by sarah-colq** [comment]
The usmap package we use in the R package doesn't currently have Puerto Rico.  There is a pull request to add it on the package, but there are build problems: https://github.com/pdil/usmap/pull/34.

**Comment by capnrefsmmat** [comment]
@sarah-colq Is this resolved by your changes to use shapefiles, or are there still cases that are missing Puerto Rico?

**Comment by sarah-colq** [comment]
The bubble plots don't have it yet.

**Comment by sarah-colq** [comment]
Bubble plots now have PR.
