### ISSUE TITLE
Empty messages emitted by covidcast_signal() when queries fail to return data

### ISSUE THREAD

**Issue by huisaddison** [cmu-delphi/covidcast#245]
See @capnrefsmmat 's comment below: happens more generally when queries fail to return data.

Case 1: `as_of < start_day` covidcast_signal() does (properly) return an empty dataframe.  However, it first emits a series of newlines; it could instead automatically catch this edge case, immediately return (and also not emit a bunch of newlines).

To reproduce:

```
library(covidcast)

start_day = "2020-04-15"
end_day = NULL

covidcast_signal("doctor-visits", "smoothed_adj_cli",
                 start_day, end_day,
                 as_of='2020-01-01')
```

Case 2: `as_of = '2020-10-01'` -- fetches data up to `2020-09-27`, and then emits a bunch of newlines.  

```
[...]
Fetched day 20200910: 1, success, num_entries = 1880
Fetched day 20200911: 1, success, num_entries = 1884
Fetched day 20200912: 1, success, num_entries = 1865
Fetched day 20200913: 1, success, num_entries = 1796
Fetched day 20200914: 1, success, num_entries = 1789
Fetched day 20200915: 1, success, num_entries = 1902
Fetched day 20200916: 1, success, num_entries = 1987
Fetched day 20200917: 1, success, num_entries = 1972
Fetched day 20200918: 1, success, num_entries = 1954
Fetched day 20200919: 1, success, num_entries = 1931
Fetched day 20200920: 1, success, num_entries = 1851
Fetched day 20200921: 1, success, num_entries = 1838
Fetched day 20200922: 1, success, num_entries = 1908
Fetched day 20200923: 1, success, num_entries = 1869
Fetched day 20200924: 1, success, num_entries = 1828
Fetched day 20200925: 1, success, num_entries = 1794
Fetched day 20200926: 1, success, num_entries = 1727
Fetched day 20200927: 1, success, num_entries = 1619

































There were 33 warnings (use warnings() to see them)
```

Case 3: `as_of = '2020-05-01`, whereas `start_date='2020-04-15'` - also a bunch of empty newlines.

**Comment by capnrefsmmat** [comment]
The newlines appear in other cases where queries fail to return data, but I don't know what is emitting them. Any idea what part of the code might be responsible?

**Comment by huisaddison** [comment]
Haven't dug into the source code, just wanted to document it in case others just didn't know / so I can look into it later.  It's more of an aesthetic annoyance than a critical bug, so if it doesn't get tackled by an eng team member by the time I finish the DAP(s) I'm assigned, I could look into it

**Comment by huisaddison** [comment]
Found the bug...  happens inside message(sprintf(...)).  When message(sprintf(...)) encounters a NULL, it emits a newline without any warnings or errors.  Go figure.

```
> x = list()
> x$foobar
NULL
> message(sprintf('test: %s', x$foobar))

>
```

My guess is that when data isn't available, at least one of `dat[[i]]${result, message, epidata}` is NULL.

https://github.com/cmu-delphi/covidcast/blob/main/R-packages/covidcast/R/covidcast.R#L497-L501

**Comment by huisaddison** [comment]
@capnrefsmmat I'm not rapid enough at R package development (develop-test-debug within the package environment to do this quickly otherwise I'd issue a PR.... but it seems simple enough to move the linked code block to be inside the `if success` block (if that's what we want to do.  Otherwise a suitable code block to catch the NULLs before they go into sprintf... Again if we don't have the resources to fix this I can look into it after the DAPs (which probably means mid-December)

**Comment by capnrefsmmat** [comment]
Ah, weird. I bet moving it inside the `if` will solve it, since `$epidata` will indeed be null in the error case. @benjaminysmith or @JedGrabman, do one of you want to take this as a low-priority bugfix?

**Comment by benjaminysmith** [comment]
Yeah I can give it a shot.
