### ISSUE TITLE
Error: 'relocate' is not an exported object from 'namespace:dplyr'

### ISSUE THREAD

**Issue by gtzwang** [cmu-delphi/covidcast#253]
Hi, thanks for fixing the msg issue. The basic test is still not working though. Getting this error:
**Error: 'relocate' is not an exported object from 'namespace:dplyr'**. 

> covidcast_signal(data_source = "fb-survey", signal = "smoothed_cli", 
+                                        start_day = "2020-05-01", end_day = "2020-05-07", 
+                                        geo_type = "county")
Fetched day 2020-05-01: 1, success, num_entries = 1052
Fetched day 2020-05-02: 1, success, num_entries = 1032
Fetched day 2020-05-03: 1, success, num_entries = 1021
Fetched day 2020-05-04: 1, success, num_entries = 1024
Fetched day 2020-05-05: 1, success, num_entries = 993
Fetched day 2020-05-06: 1, success, num_entries = 998
Fetched day 2020-05-07: 1, success, num_entries = 960
**Error: 'relocate' is not an exported object from 'namespace:dplyr'**

**Comment by capnrefsmmat** [comment]
relocate was [added in dplyr 1.0.0](https://www.tidyverse.org/blog/2020/06/dplyr-1-0-0/#new-features); you may want to do `install.packages("dplyr")` to get the latest version.

**Comment by gtzwang** [comment]
Confirmed. works now. Thanks.
