### ISSUE TITLE
Add CITATION file to R client

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#273]
R packages can contain a [CITATION file](https://cran.r-project.org/doc/manuals/R-exts.html#CITATION-files) so that users can type `citation("covidcast")` and get a recommended citation, both in plain text and BibTeX formats.

Once we add this, we should make the home page of the pkgdown site list the citation as well.

This will require deciding on what the citation should be.

**Comment by capnrefsmmat** [comment]
The auto-generated citation for the package is now pretty good, so our focus here should be to ensure the CITATION explains how to cite the *data* as well. And add our paper to it, once it's available.

**Comment by capnrefsmmat** [comment]
Data licensing and citation are given here: https://cmu-delphi.github.io/delphi-epidata/api/covidcast_licensing.html

We can just include a reference to this somehow, and also make sure the documentation mentions it by giving the citation clearly on the home page (or similar discoverable place).

**Comment by statsmaths** [comment]
Fixed in #503.
