### ISSUE TITLE
Parallelize covidcast_signal()?

### ISSUE THREAD

**Issue by huisaddison** [cmu-delphi/covidcast#279]
I noticed that covidcast_signal() can be slow; but the operation is easily parallelizable using a tool like parallel::mclapply().  (I realized this after I wrapped single-day covidcast_signal() queries in such a parallel operation, and I basically get a nice n_core times speedup).

I quickly sketched PR draft #278 to give an idea for how we could stick this inside the package, and if it is a good idea (reasons I can think of for it being a "bad idea": parallelism is finicky enough that maybe we prefer to defer it to an end user...) then I (or somebody else interested) can put some time into building, testing, etc.

**Comment by capnrefsmmat** [comment]
So #275 will independently speed up API requests for anything other than county level, by letting us batch requests across days.

Did you test this and find that it actually speeds things up? It seems like it would depend on what the bottleneck is. If you're downloading data as fast as your Internet connection can handle, this won't help. If the server is providing data more slowly than that, multiple connections will maybe get you multiple servers in our AWS pool. Not sure if we want to let individual clients have many simultaneous connections and perhaps overwhelm the pool.

**Comment by huisaddison** [comment]
I did see #275 and I think it's a great addition.  Anecdotally I did find a speedup (even on my rinky-dink 4 core laptop).  I can provide some timings, varying n_core, to give some more color as to how useful this could be.

**Comment by capnrefsmmat** [comment]
@huisaddison The speedups in #275 are now available on the r-pkg-devel branch if you'd like to test them out. Then we can evaluate if parallelization is beneficial or if the improvements in #275 are sufficient. They'll make state, MSA, and HRR-level downloads much faster, by packing in more days per API call; county-level estimates for dense signals like cases and deaths will still take roughly the same time as before.
