### ISSUE TITLE
Investigate efficiency updates for evaluate_predictions

### ISSUE THREAD

**Issue by JedGrabman** [cmu-delphi/covidcast#295]
[evaluate_predictions](https://github.com/cmu-delphi/covidcast/blob/2443c31356c30c2c692bce834bea6cae2a5c2083/R-packages/evalcast/R/evaluate.R#L49) is rather slow. The cause seems to be this loop in [`evaluate_predictions_single_ahead`](https://github.com/cmu-delphi/covidcast/blob/2443c31356c30c2c692bce834bea6cae2a5c2083/R-packages/evalcast/R/evaluate.R#L141-L146):
```
  for (err in names(err_measures)) {
    score_card <- score_card %>%
      rowwise() %>%
      mutate(!!err := err_measures[[err]](.data$forecast_distribution, .data$actual)) %>%
      ungroup()
  }
```
and the mutate line in particular.

This may just be a case of using expensive functions on large quantities of data. I do see some comments online discouraging the use of rowwise and it's possible that our error measurement functions could be improved as well, although I haven't looked into them yet.

**Comment by dajmcdon** [comment]
I'm going to close this. I think it's fixed without the cards.
