### ISSUE TITLE
evalcast tests are noisy / have a lot of warnings

### ISSUE THREAD

**Issue by JedGrabman** [cmu-delphi/covidcast#301]
evalcast tests have a lot of non-actionable warnings, e.g.

```
test-basic-functionality-runs-without-error.R:12: warning: get_predictions and evaluate_predictions on baseline_forecaster works
Data not fetched for the following days: 2020-07-20

test-basic-functionality-runs-without-error.R:12: warning: get_predictions and evaluate_predictions on baseline_forecaster works
Data not fetched for the following days: 2020-08-10

test-basic-functionality-runs-without-error.R:12: warning: get_predictions and evaluate_predictions on baseline_forecaster works
Data not fetched for the following days: 2020-08-10

test-basic-functionality-runs-without-error.R:35: warning: geo_values argument to get_predictions works
Data not fetched for the following days: 2020-07-20
```
We should probably be mocking out some calls so that we aren't relying on real data and instead only testing the functionality within evalcast.

**Comment by dajmcdon** [comment]
Generically need better tests that don't require constant API queries

**Comment by capnrefsmmat** [comment]
You may find [httptest](https://enpiar.com/r/httptest/index.html) useful so you can use fixed test data instead of relying on the API not changing its outputs. We use this in the covidcast R package, so you can see some examples there.
