### ISSUE TITLE
Need support for requesting weekly data to R and Python clients for safegraph patterns

### ISSUE THREAD

**Issue by benjaminysmith** [cmu-delphi/covidcast#305]
See https://github.com/cmu-delphi/covidcast-indicators/issues/367#issuecomment-729773986 for context

**Comment by capnrefsmmat** [comment]
First question: how should we handle the `time_value`? It will be an integer in YYYYWW format, apparently. We can use a package to convert back to a datetime. Should we turn it into the *first* day of the epiweek? Or add an extra column so we can store both the start and end of the epiweek?

**Comment by chinandrew** [comment]
Are there practical reasons some people may want the start of the week vs the end? e.g. if everyone just uses the start, seems like we might be able to keep things simple and just use the first day. If it's pretty common people want both and we don't want them to have to add 6 days to get the end (although that doesn't seem like a huge lift), it doesn't seem too bad to have a different return format if the time format is different.

**Comment by capnrefsmmat** [comment]
For the R package, we'll also need to update `covidcast_meta()` to handle transforming the date column for weekly data correctly.

**Comment by capnrefsmmat** [comment]
Released in 0.4.0.
