### ISSUE TITLE
Clean up plotting functions

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#314]
`evaluate_predictions()` expects one forecaster and one forecast date but accommodates different aheads. 

Suppose I have `pcards` from the covidhub-ensemble for one date and aheads 1:4
```
ensemble <- evaluate_predictions(pcards) # returns list of length 4
plot_calibration(ensemble[[1]]) # works
plot_callibration(ensemble[1]) # fails
plot_coverage(ensemble[[1]]) # fails
plot_coverage(ensemble[1]) # works
```

Both functions only handle one `ahead` at a time, and fail if I pass in `ensemble`. They facet over forecast dates, though `evaluate_predictions()` won't work easily on such. `plot_width()` is the same as `plot_calibration()`

`plot_measure()` documentation says "all on the same forecasting task" but it allows different forecast dates (though not aheads) and different forecasters.

`plot_trajectory()` allows different aheads, forecasters, forecast dates, and locations.

**Comment by sgsmob** [comment]
What is the desired behavior for `plot_calibration()` and `plot_coverage()`?  My best guess:
- Expect a list of cards rather than a single card
- Handle multiple `ahead`s, creating one plot per `ahead` value
- Handle only one forecaster
- Handle only one forecast date
