### ISSUE TITLE
Expose access to the API endpoint used for R covidcast client queries

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast#317]
It is possible to direct the Python covidcast client at an alternative API endpoint like so:

```
import covidcast
covidcast.covidcast.Epidata.BASE_URL = "https://[something_else]/epidata/api.php"
```

However R places tighter controls on library innards. The closest I could get was the following, which errors out:

```
> library(covidcast)
> environment(covidcast_signal)$COVIDCAST_BASE_URL <- "https://[something-else]/epidata/api.php"
Error in environment(covidcast_signal)$COVIDCAST_BASE_URL <- "https://[something-else]/epidata/api.php" : 
  cannot change value of locked binding for 'COVIDCAST_BASE_URL'
```

For purposes of giving folks advanced access to prototype signals that are not yet available from the public API, it would be nice if the R client could accept an alternative API endpoint address.

**Comment by chinandrew** [comment]
Is the best way to do this just add an optional api_url argument? Or is there some fancy R pattern for doing this.

**Comment by krivard** [comment]
If we don't want to clutter the public namespace (and we probably don't -- this would be for internal signal releases only) probably best to use a fancy R pattern, if one exists. Fussing about with environments is already reaching the limits of my R expertise though, and that didn't work ☹️

**Comment by capnrefsmmat** [comment]
We could use R's `options()` mechanism and let the user set `options(covidcast.api.url = something)`, and check if the option is set when making API requests.

**Comment by capnrefsmmat** [comment]
This should now be possible with the beta version on `r-pkg-devel`. Just set

```r
library(covidcast)
options(covidcast.base_url = "https://[something_else]/epidata/api.php")
```

To reset to the production server, use `options(covidcast.base_url = NULL)`.
