### ISSUE TITLE
Use `covidcast_signals()` (plural form) in evalcast

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/covidcast#343]
Hi all, cc @dajmcdon.  Due to some development that's occurred on the covidcast side, we should use `covidcast_signals()` (note the plural form), within evalcast in order to fetch multiple signals.  This function returns a list of signals, and the covidcast package provides various utilities for wrangling them, [as demonstrated in this vignette](https://cmu-delphi.github.io/covidcast/covidcastR/articles/multi-signals.html).  

So as far as I can tell this means we'd change `get_predictions_single_date()` to call a single function `download_signals()` (note the plural form), rather than perform `map_dfr()` and call `download_signal()`.  And the new function `download_signals()` would simply call `covidcast_signals()` and then call `aggregate_signals()` with `format = "long"`.  This would just simplify the code used in evalcast.

**Comment by dajmcdon** [comment]
I just implemented this on the branch I'm currently on, and it seems to work with no problems (apart from the messages annoyingly printing on one line). Is it ok to wait to put it on main/evalcast when I do a PR with a bunch of other things, or are you being slowed down elsewhere?

**Comment by ryantibs** [comment]
Thanks, and sure, it's not slowing me down elsewhere.

**Comment by ryantibs** [comment]
Hi @dajmcdon a question for you.  What do you think about allowing the `forecaster` (function that `get_predictions()` calls to get forecaster) to take as its first argument a list of data frames?  Rather than a single long data frame?

In previous discussions on the covidcast side (cc @chinandrew @capnrefsmmat), we deiced that for multiple signals, it's not clear that "long" is more canonical than "wide".  Both are useful.  Hence the `covidcast_signals()` data frame returns a list of data frames, and `aggregate_signals()` allows you to turn them into either "long" or "wide".  (There's also specialized pivot functions we provide to go back and forth).

So if you give `forecaster` a list of signal data frames, then it could just call `aggregate_signals()` directly in order to get it in the format it prefers.  

AND the advantage of this is that `aggregate_signals()` allows you to specify time shifts to append for any of the signals.  Currently for my own use case, the first thing I'm doing is taking the long data frame, splitting it up into a list of individual signal data frames, then calling `aggregate_signals()` to get shifts (and to turn it into wide format).  I think it would be more convenient just to get a list in the first place.  What do you think?

**Comment by dajmcdon** [comment]
The evalcast documentation isn't very specific in terms of the format the forecaster should expect. And when we add functionality for the combination with side data (or maybe even exclusively side data) it could be more complicated. 

If I were writing a forecaster, I think I'd prefer the list for ease of differential processing across signals. But I think lots of users tend to think in wide. I'm also mindful of backward compatibility (unprocessed long df), but I like the simple functionality of `aggregate_signals()` and the conversion functions. 

What if we try to give the user options: add two arguments to `get_predictions()` with a default of `long` with no processing for backward compatibility but allow wide or list as the other options with optional lists of processing?

**Comment by ryantibs** [comment]
I think that sounds fine, though I'm not sure we need to keep "long" the default just for backwards compatibility.  Is anybody using evalcast outside of Delphi (honest question)?  This new change would just require setting (say) `format = "long"` in `get_predictions()`, with the options being "list", "wide", "long".
