### ISSUE TITLE
Add R 3.5 check for covidcast that skips problematic tests

### ISSUE THREAD

**Issue by chinandrew** [cmu-delphi/covidcast#350]
Some of the vdiffr plotting tests don't work the same on 3.5 due to how the SVG is encoded, but the output image is visually the same. We're changing the hCI to run on 3.6, but since the package is 3.5+, this task is to add a 3.5 CI workflow and a condition to the tests so they only run on 3.6+

cc @sarah-colq @capnrefsmmat

**Comment by statsmaths** [comment]
The test suite now checks for version 4.x.x, which matches the version used to create the plots, so this should be resolved.
