### ISSUE TITLE
Evalcast killcards identifies cumulative predictions as incidence predictions

### ISSUE THREAD

**Issue by JedGrabman** [cmu-delphi/covidcast#351]
The killcards branch treats all predictions as incidence predictions, even if they are actually cumulative. 
For example, 

```
yyg_results = get_covidhub_predictions("YYG-ParamSearch", "2020-07-20")
yyg_results %>% filter(quantile == 0.01) %>% filter(location == "01") %>% filter(ahead == 1)

# A tibble: 2 x 10
  ahead location quantile  value forecaster      forecast_date data_source signal               target_end_date incidence_period
  <int> <chr>       <dbl>  <dbl> <chr>           <date>        <chr>       <chr>                <date>          <chr>           
1     1 01           0.01   82.2 YYG-ParamSearch 2020-07-20    jhu-csse    deaths_incidence_num 2020-07-25      epiweek         
2     1 01           0.01 1357.  YYG-ParamSearch 2020-07-20    jhu-csse    deaths_incidence_num 2020-07-25      epiweek 
```
While their actual predictions ([from here](https://raw.githubusercontent.com/reichlab/covid19-forecast-hub/master/data-processed/YYG-ParamSearch/2020-07-20-YYG-ParamSearch.csv)) are: 
```
2020-07-20,1 wk ahead inc death,2020-07-25,01,quantile,0.01,82.21883237695901
...
2020-07-20,1 wk ahead cum death,2020-07-25,01,quantile,0.01,1356.7201170395094
```

It looks like we're only checking for deaths vs cases, but don't distinguish between cumulative and incidence stats. [See here](https://github.com/cmu-delphi/covidcast/blob/3950307bbcf503e9e15cf25610a9aeb6d88f6106/R-packages/evalcast/R/get_covidhub_predictions.R#L46-L55).

```
    pcards[[forecast_date]] <- pred %>%
      separate(.data$target,
               into = c("ahead", NA, NA, NA, "response"),
               remove = TRUE) %>%
      mutate(forecaster = covidhub_forecaster_name, 
             incidence_period = 'epiweek',
             data_source = "jhu-csse",
             ahead = as.integer(ahead),
             signal = if_else(.data$response=="death",
                                     "deaths_incidence_num",
                                     "confirmed_incidence_num"))
```

**Comment by JedGrabman** [comment]
CC: @dajmcdon

**Comment by dajmcdon** [comment]
Good catch. I inadvertently deleted 
```r
filter(str_detect(.data$target, "wk ahead inc")) %>%
```
It needs to go right before the `separate()` call.

**Comment by dajmcdon** [comment]
We don't have any utilities that would handle the cumulative forecasts in the package currently. The various aggregations only handle "epiweek" cumulatives, but not more. I think until someone balks, we can continue to filter those out, but we should probably add a note to the documentation @sarah-colq

**Comment by jacobbien** [comment]
Hi @dajmcdon.  As far as I'm aware, we do handle day-level cumulative forecasting.  All one would do is set `incidence_period = "day"` and then choose a cumulative signal from covidcast.  In issue #120, I was suggesting that we have vignettes that demonstrate how cumulative forecasting would go. (@JedGrabman - sorry just realized I haven't given you feedback on the vignette yet!)

**Comment by dajmcdon** [comment]
The bug should be fixed now, given recent pushes: cumulative forecasts are again removed in `get_covidhub_predictions()`.

If `evalcast` runs the forecaster and names the response correctly, cumulatives should just "work". This branch also allows "side_data" in `evaluate_predictions()` so you could manually add your own response if you really wanted. Do you think it's worth modifying `get_covidhub_predictions()` to name the response correctly for the cumulatives rather than just dumping them? I'm not sure of the exact combinations at the moment that would let all the downstream stuff run.

**Comment by jacobbien** [comment]
I do think it's worth it and not that hard (Easy for me to say if I'm not doing it...).  To be specific: for death, one would set the response signal to be `deaths_cumulative_num` instead of `deaths_incidence_num` and for cases, one would set the response signal to be `confirmed_cumulative_num` instead of `confirmed_incidence_num`.  As far as I can remember everything downstream should then just work.

**Comment by dajmcdon** [comment]
*Follow up* 

As far as I can tell, there are no cumulative case forecasts in Zoltar. We should be able to check if this changes with:

```r
zoltar_connection <- zoltr::new_connection()
zoltr::zoltar_authenticate(zoltar_connection, Sys.getenv("Z_USERNAME"),Sys.getenv("Z_PASSWORD")) 
# there's a demo version I'm not posting, so this won't run
the_projects <- zoltr::projects(zoltar_connection)
project_url <- the_projects[the_projects$name == "COVID-19 Forecasts", "url"]
all_targets <- zoltr::targets(zoltar_connection, project_url)
unique(all_targets$unit)
```
There's also hospitalizations, but I'm not sure what to do with this. 

Current implementation on `evalcast-killcards` pulls the other 3 as desired. I think we still need to fix the `evaluate_predictions()` family to grab the right truth data as suggested above.
