### ISSUE TITLE
Vignette updates for evalcast

### ISSUE THREAD

**Issue by JedGrabman** [cmu-delphi/covidcast#355]
@jacobbien left some comments for suggested changes to the evalcast vignette [here](https://github.com/cmu-delphi/covidcast/pull/155)

It might be worth combining this work with any documentation changes that need to be made for the changes on the `evalcast-killcards` branch

**Comment by dajmcdon** [comment]
@JedGrabman @sarah-colq If you have some cycles, can you try to address Jacob's comments at the link above?
