### ISSUE TITLE
Switch the API clients to use POST requests

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#362]
If you request a *lot* of geo_values, the GET query can be too long, and you get Request-URI Too Long (HTTP 414) from the API server.

Fortunately the server seems to support POST with no modification. We should switch the clients to POST and test thoroughly. (Not sure what this will do to the R httptest tests...)

**Comment by chinandrew** [comment]
The Python package uses `delphi-epidata` to make requests, so this should belong there. I'll open a PR for it.

**Comment by capnrefsmmat** [comment]
Released in 0.4.0.
