### ISSUE TITLE
R package `jsonlite` version 1.7.2 returning 404, causing covidcast R installation to fail

### ISSUE THREAD

**Issue by capolitsch** [cmu-delphi/covidcast#376]
The latest jsonlite R package version 1.7.2 is returning 404 on CRAN, which is causing covidcast installation to fail for users who don't already have a version of jsonlite installed on their machine. The latest version was published 2 days ago, so it may not be stable.

https://cran.rstudio.com/bin/macosx/contrib/4.0/jsonlite_1.7.2.tgz

We might want to specify jsonlite=1.7.1 as the dependency for now.

**Comment by capnrefsmmat** [comment]
See also https://github.com/jeroen/jsonlite/issues/342

I'm not sure there's a way we can avoid this -- is there any way to request specific package versions in `DESCRIPTION`?

**Comment by jacobbien** [comment]
We could do this through GitHub and the remotes package...

https://github.com/r-lib/remotes

**Comment by chinandrew** [comment]
1.7.2 Installs fine for me now.

**Comment by jacobbien** [comment]
Apparently `jsonlite (== 1.7.1)` would work (although it's discouraged): https://r-pkgs.org/description.html?q=versioning#versioning

**Comment by capolitsch** [comment]
1.7.2 works for me now
