### ISSUE TITLE
HRR and MSA data not showing up properly in choropleth plots for covidcast

### ISSUE THREAD

**Issue by sarah-colq** [cmu-delphi/covidcast#381]
The data showing up in the R version looks different than the Python version.  We presume the R version is wrong because it was behaving before using the shapefiles instead of usmap.

**Comment by capnrefsmmat** [comment]
Could you say what specifically seemed wrong? I just made an  MSA plot where I set all MSAs to have 0 values except a couple, and their values appeared in the correct places.

**Comment by chinandrew** [comment]
We stumbled upon it while debugging the svg issue, [slack post here](https://delphi-org.slack.com/archives/C01E5M9KVN1/p1606757739002300?thread_ts=1606260372.020300&cid=C01E5M9KVN1)

**Comment by sarah-colq** [comment]
@capnrefsmmat Can we close this?

**Comment by capnrefsmmat** [comment]
I think so, but worth double checking. My fix only affected HRR maps, and when I plotted MSA maps with the current version of the package on `r-pkg-devel`, they looked fine. If they also look fine to you, then I think we're fine to close this
