### ISSUE TITLE
Expected signal format for baseline_forecaster()

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/covidcast#391]
I'm using the version of evalcast on the evalcast-killcards branch, and `baseline_forecaster()` looks like it's expecting data in `signal_aggregation = "long"` format, but this isn't documented anywhere.  I confirmed this by setting `signal_aggregation = "wide"` (or "list") in examples, and it throws errors.  We should document the need for "long" format (or probably even better, allow it to flexibly operate on any format).

**Comment by ryantibs** [comment]
While I'm here, I may as well mention that in all my examples `baseline_forecaster()` produces fine values for WIS, when its predictions are run through `evaluate_predictions()`, but always produces `NA` values for AE.  I haven't dug into what may be the issue here.

**Comment by dajmcdon** [comment]
The first should be fixed now. The second is also fixed assuming that #392 fixes it.
