### ISSUE TITLE
Bug in absolute_error()

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/covidcast#392]
On the evalcast-killcards branch, there appears to be a fatal bug in the `absolute_error()` function. This line: https://github.com/cmu-delphi/covidcast/blob/3da0b3b8a0154e734f101822d59aa0bb55a1d65d/R-packages/evalcast/R/err_measures.R#L81
Should instead be 
```
ae <- abs(actual - value)
```
right? (My understanding is that `quantile` contains the probability level associated with the quantile value, which is stored in `value`.)

I think this explains why any point forecaster, that has `quantile = NA`, is going to produce an NA value for absolute error, as I raised in #391 for `baseline_forecaster()`.

**Comment by dajmcdon** [comment]
This should be fixed now.
