### ISSUE TITLE
`download_signals()` failures

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#399]
From Ryan:

I’ve encountered weird bugs running `get_predictions()`  in some cases where I think what’s happening is that training data for the forecaster “as of” the given forecast date wasn’t available at all.  I think this is a failure in `download_signals()`, where it probably tries to manipulate an empty object or something like that, instead of catching that it got back an empty data frame `covidcast_signals()`.  This is just my guess; aside from just looking at download_signals() to see if you can anticipate the problem you could try to call `get_predictions()` with the baseline forecaster for cases data from USAFacts at the start of June.  This is what I was doing (if my memory serves me right) before I ended up switching to JHU.

**Comment by dajmcdon** [comment]
The problem seems to be that there is no data in the API for with a pre-June `as_of`. That's because we didn't have data at that point.

I think we should (potentially) do two things:

1. Stop completely with an interpretable error if download_signals() returns no data. Should be implemented [around here](https://github.com/cmu-delphi/covidcast/blob/e0f4457619c7f98b96ca16a3208f41473a74f74f/R-packages/evalcast/R/get_predictions.R#L127). This should explain that, given the desire to do proper backtesting, you wouldn't actually be able to make predictions at that time. We can’t anticipate what the forecaster would return, so it would be difficult to, for example, return empty predictions for that forecast date and try others.
1. Add an argument to `get_predictions()` that overrides the `as_of` and strongly discourage using it in the documentation. To a large degree, doing this eliminates the purpose of `evalcast`. Now we're just downloading current data and running a forecaster on it, so you should just use `covidcast` plus your forecaster.

I’m tagging @jacobbien in case there’s something I’m not thinking of. We should definitely do 1. I'm less convinced that 2. is a good idea.

**Comment by dajmcdon** [comment]
Rereading Ryan's initial comment, it sounds at least possible that the error happens inside `download_signals()` before the [linked line](https://github.com/cmu-delphi/covidcast/blob/e0f4457619c7f98b96ca16a3208f41473a74f74f/R-packages/evalcast/R/get_predictions.R#L127). Probably still not interpretable. @sarah-colq can you verify where it happens?

**Comment by sarah-colq** [comment]
It does happen inside `download_signals()`.  It happens during the call to `aggregate_signals()` from covidcast.  'covidcast_signals()` returns an empty list and then `aggregate_signals()` cannot handle an empty list.  I can modify `download_signals()` that if `covidcast_signals()` returns an empty list an error is thrown.  

I don't think 2 is a good idea.  1 would indicate that there is no data and that you should remove that forecast_date from your backtesting.  Evalcast is supposed to be for backtesting, and as you said there is a simple enough way to do number 2 another way. 

I will implement #1.

**Comment by dajmcdon** [comment]
Sounds good (not implementing 2).
