### ISSUE TITLE
Add a function `get_actuals()`

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#401]
This should just be the `evaluate_predictions()` function with no evaluation. Just add a column to the predictions card with the observed values.

- [ ] Should be exported and documented.
- [ ] Adjust `evaluate_predictions()` to call this first.

**Comment by JedGrabman** [comment]
Implemented in Pull Request #408. However, I reversed the approach.  `get_actuals` calls `evaluate_predictions` while specifying that it wants no error measures.
