### ISSUE TITLE
Update tests for evalcast

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#402]
I've been holding off on this because it will take some work. We need tests for the basic package functionality. Some of these existed before, but take too long to run. Currently, those are turned off. We need to turn them back on.

There are two issues. 

1. We don't want to call the API to run the tests. Alex suggested using a combination of the `mockery` and `httptest` packages. Useful also to consult the `covidcast` [tests](https://github.com/cmu-delphi/covidcast/blob/evalcast/R-packages/covidcast/tests/testthat/test-covidcast.R).
2. Some of the basic functionality involves slow repeated calls (running baseline forecaster multiple times with slightly different arguments, say) and then running those results through lots of tests. This is not really ideal for package development since the checks will take forever. We should likely use "test fixtures". See [this vignette]()https://testthat.r-lib.org/articles/test-fixtures.html#test-fixtures).

**Comment by sgsmob** [comment]
Is this for the `evalcast-killcards` branch only or do we need to apply this to other branches?

**Comment by dajmcdon** [comment]
`killcards` only.

**Comment by sgsmob** [comment]
What is the intended behavior of `get_predictions` when `signals$start_day` contains a mix of dates and functions?  (see [this test](https://github.com/cmu-delphi/covidcast/blob/e0f4457619c7f98b96ca16a3208f41473a74f74f/R-packages/evalcast/tests/testthat/test-basic-functionality-runs-without-error.R#L143)).  From the test it seems like we want to apply the function selectively but the `get_predictions_single_date()` function (see [here](https://github.com/cmu-delphi/covidcast/blob/e0f4457619c7f98b96ca16a3208f41473a74f74f/R-packages/evalcast/R/get_predictions.R#L103)) seems to only work if the dates are wrapped in lists too.  Did we expect that this functionality is not enabled?

**Comment by dajmcdon** [comment]
Yeah, there probably needs to be an `else` there right (if not a function)?

**Comment by JedGrabman** [comment]
Nat mentioned that `mockr` may be a more stable/better maintained option than `mockery`.

**Comment by sgsmob** [comment]
Yes, it was used on #414
