### ISSUE TITLE
New evalcast vignettes

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#403]
I think we need 2 more vignettes

1. A demonstration of forecasting with side data, potentially only side data. And also evaluating with the same. We can probably just run the baseline forecaster on something or else use Ryan's `modeltools`
2. A more complete demonstration of some of the plotting. Particularly the trajectory plots, but perhaps also stuff from @JedGrabman notebook.

**Comment by dajmcdon** [comment]
See here for possible version of 2: #389

**Comment by brookslogan** [comment]
It would be helpful to include some of the vignette material in `@examples` as well.  I think some of the details of what forecasting functions are or the baseline forecaster assumptions might only be in the existing vignette but not the documentation (plus some of the vignette code would be nice to have pop up from `help` as well).
