### ISSUE TITLE
Add MSA maps in Python package

### ISSUE THREAD

**Issue by chinandrew** [cmu-delphi/covidcast#41]
Currently geo/plotting functions  only support state and county. Add support for MSAs as well. Blocked by #38

**Comment by chinandrew** [comment]
@capnrefsmmat Do we just want metropolitan statistical areas only, or also micropolitan areas? Collectively they make up [ core based statistical areas](https://en.wikipedia.org/wiki/Core-based_statistical_area), and it's not hard to separate them out in the census file.

The website seems like metro-only. I can i) leave them both in, ii) make it an argument as to which one/both to use, defaulting to metro, or iii) just do metro. Don't see much harm in doing (ii), unless no one cares about micro.

**Comment by capnrefsmmat** [comment]
> EDIT: just looked into this some more and looks like we only return metro and not micro, so going to just do metro.

Yes, exactly -- we only produce estimates for metropolitan statistical areas, not micropolitan ones.

The Census data included in the R package (with population estimates and such) includes all of them, including micropolitan, but there's a column that lets you filter by type.
