### ISSUE TITLE
Fix most R check warnings/notes

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#415]
CHECK currently barfs lots of messages like these:

```
  abbr_to_fips: no visible binding for global variable ‘STATE’
  abbr_to_name: no visible binding for global variable ‘STATE’
  apply_shifts_one: no visible binding for global variable ‘geo_value’
  apply_shifts_one: no visible binding for global variable ‘time_value’
  apply_shifts_one: no visible global function definition for ‘:=’
  apply_shifts_one: no visible binding for global variable ‘value’
  cbsa_to_name: no visible binding for global variable ‘LSAD’
  covidcast_cor: no visible binding for global variable ‘geo_value’
  covidcast_cor: no visible binding for global variable ‘time_value’
  covidcast_cor: no visible binding for global variable ‘value.x’
  covidcast_cor: no visible binding for global variable ‘value.y’
  covidcast_days: no visible binding for global variable ‘time_value’
```

Most of these are because we're using dplyr operations and R can't tell from static analysis that the variable names are actually column names. We can [use `.data$` to avoid this](https://dplyr.tidyverse.org/articles/programming.html#eliminating-r-cmd-check-notes).

Someone should go through, add `.data` wherever needed, ensure all tests pass and `devtools::check()` no longer complains, and add any `@importFrom` calls needed for other missing bindings (like `:=` above, not sure where that's from).

**Comment by statsmaths** [comment]
This was fixed as part of one of the pushes we made to getting all of the notes resolved.
