### ISSUE TITLE
Remove dependency on usmap

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#420]
The usmap package was [removed from CRAN](https://cran.r-project.org/web/packages/usmap/index.html) because of some [unfixed errors introduced by a new R change](https://github.com/pdil/usmap/issues/44). This renders covidcast not installable for anyone who doesn't already have usmap installed.

@sarah-colq says we only use usmap for bubble plots, so we can switch to use the same strategy we use for choropleths. We should make this the highest-priority change to the package, because nobody will be able to use our package, and this might start having impact on our automation soon if we get new dev machines or reinstall environments or anything like that.

**Comment by pdil** [comment]
I'm very sorry for the inconvenience. `usmap` is back on [CRAN](https://cran.r-project.org/package=usmap) if you choose to use it again.
