### ISSUE TITLE
Use API instead of HTML parsing when retrieving forecast dates

### ISSUE THREAD

**Issue by JedGrabman** [cmu-delphi/covidcast#436]
`evalcast::get_covidhub_forecast_dates` does html parsing to find what dates a forecaster has submitted for. This breaks if github changes the html of pages they return (which they appear to have just done). I'm making a quick fix to look for the new html, but the longer term solution is to use the github API and retrieve the file names instead.

**Comment by jacobbien** [comment]
Just want to connect this issue to the previous issue #99.

**Comment by JedGrabman** [comment]
Using the Zoltar API may be preferable to the Github API since it's already used in the package and we could potentially transition to using `get_zoltar_predictions` as well.
