### ISSUE TITLE
Coverage plots do not work with default evalcast objects

### ISSUE THREAD

**Issue by JedGrabman** [cmu-delphi/covidcast#444]
Coverage plots require quantile predictions and values. Currently, evalcast stores quantile predictions in prediction cards and actual results in score cards, but there is no default object and a join is required.

Suggested Fixes

1.) Have the plots take in a predictions card object and automatically retrieve the appropriate scores
OR
2.) Have the plots take in a predictions card and score card object.

1 is nicer for Covidcast users, but wouldn't work for any users with external data.

**Comment by JedGrabman** [comment]
Related, faceted plots interact oddly with NA data. I believe it attempts to filter down to a common set of values (i.e. so it's presenting a plot on the same geo_values, etc.) but it doesn't take into account NA's while doing this. This means that having NA's when ahead=2 can change what your plot for ahead=1 looks like, because it changes the filtering. Also, a user may not want any filtering in some cases and they currently have no ability to control that.

**Comment by dajmcdon** [comment]
Let's change `plot_coverage()` to take the predictions_cards and then call `get_actuals()`.
