### ISSUE TITLE
evalcast vignette fails

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#449]
I think it's mainly outdated. First error was on `collapse_cards()`, but this is no longer used. Second error was

```r
plot_calibration(scorecards, type = "wedgeplot")
Error: In compute_actual_vs_nominal_prob: grp_vars must be present in the score_card. See details.
```

**Comment by dajmcdon** [comment]
Check if related to #444

**Comment by sarah-colq** [comment]
These are breaking because plot_calibration no longer works with the scorecards since they don't have quantile and value in them.

**Comment by dajmcdon** [comment]
Is the vignette good to go? Like ready for the "public"?
