### ISSUE TITLE
Evalcast Cleanup

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#450]
`plot_canonical()` has a lot of arguments

```r
plot_canonical <- function(df, x, y, aggr = mean, dots = TRUE, lines = TRUE,
                           group_vars = "forecaster", facet_rows = NULL,
                           facet_cols = NULL, base_forecaster = NULL,
                           scale_before_aggr = FALSE,
                           title = waiver(), subtitle = waiver(),
                           xlab = waiver(), ylab  = waiver(),
                           legend_position = "bottom", legend_title = NULL) {
```

Most of this handles faceting and colors and other things that are passed along optionally. The other plotting functions try to determine some of this automatically. I think we should try to make the others more like this one. There is too much "auto faceting" in the other functions.

1. Remove "auto faceting" from the other `plot_` functions.
2. Can we try to standardize the arguments and documentation? Here the first argument is `df` and the description is `dataframe containing the data to plot`. `plot_coverage()` has `scorecards` first. `plot_calibration` has `scorecard`.

**Comment by sarah-colq** [comment]
@dajmcdon Do we still want to do this?

**Comment by sarah-colq** [comment]
What I mean, the auto faceting seems to be gone, is there anything else we would need to do besides standardizing the names of variables?

**Comment by dajmcdon** [comment]
I think just do your best to standardize the arguments. So open the 5 plotting functions and compare their calls. Are they in the same order? Named the same things? Is it useful to have some arguments that are present in one function in a different function? Etc. 

If you have bandwidth, this would be helpful.

**Comment by sarah-colq** [comment]
Yeah I can do that!
