### ISSUE TITLE
Failing mockr test in evalcast

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#452]
There's a test in evalcast::test-evaluate that fails for some reason I can't track. It's commented out [starting here](https://github.com/cmu-delphi/covidcast/blob/2945b7872edd69c01f3352aeda8a62649fe981f3/R-packages/evalcast/tests/testthat/test-evaluate.R#L44) in the current code. If I try to debug locally I get other errors. @sgsmob can you check it out? Has to do with `mockr`.

**Comment by sgsmob** [comment]
The issue is that `download_signals()` is being called with county geo type rather than state.  I think it may be from #445, whic added default geo values.

The best way to debug errors like this is to add `print(mock_args(mock_download_signal))` after the call to `evaluate_predictions()`.
