### ISSUE TITLE
evalcast : memoize to disk

### ISSUE THREAD

**Issue by huisaddison** [cmu-delphi/covidcast#458]
Default behavior of `evalcast` is to memoize `download_signal()` calls to memory.  Upon loading `evalcast`, one receives the message:

```
> library(evalcast)
Calls to the `evalcast` functions `download_signal()` and
`get_covidhub_predictions()` are memoized in memory by default.
To cache to disk instead use `memoise::cache_filesystem()`. Ex:

 db <- memoise::cache_filesystem("path/to/dir/.rcache")
 download_signal <<- memoise::memoise(download_signal, cache = db)
```

However, there are two issues with this approach.  

1. `download_signal()` is not  an exported object (easy fix if one doesn't mind exposing it to the end user)
2. one is not allowed to memoise an already-memoised function.  See this error, in which I have hacked `evalcast` to export `download_signal()` on [my fork](https://github.com/huisaddison/covidcast/tree/devel/memoize):

```
> db <- memoise::cache_filesystem('covidcache/.rcache')
> download_signal <<- memoise::memoise(download_signal, cache=db)
Error: `f` must not be memoised.
```

The error arises from the `memoise()` call: https://github.com/r-lib/memoise/blob/master/R/memoise.R#L132-L134

Expected behavior: memoization to disk.

**Comment by sgsmob** [comment]
I will not be able to deal with this until at least next week to make room for forecast development

**Comment by sgsmob** [comment]
Is the expected behavior that we always memoize to disk instead of memoizing to memory?  Or to not enable memoization by default and expose the proper functions so that the user can decide for themselves?

**Comment by brookslogan** [comment]
The following seems to work to switch out the cache in something already memoized:
```
db <- memoise::cache_filesystem("path/to/dir/.rcache")
ds = evalcast::download_signal # because environment(evalcast::download_signal) <- ... produces error when called directly, but the following line does update evalcast::download_signal as well due to how environments not being copied in the same manner as other R things
environment(ds)[["_cache"]] <- db
```

**Comment by sgsmob** [comment]
So I guess I should just switch the message then?

**Comment by brookslogan** [comment]
I think your above questions remain; this is just an approach to keeping it with the same approach.  Writing to the disk without user confirmation or other action seems a bit rude, and is against [CRAN policy](https://cran.r-project.org/web/packages/policies.html) unless their temporary directory is backed by the disk (emphasis mine):

> The code and examples provided in a package should never do anything which might be regarded as malicious or anti-social. The following are illustrative examples from past experience.
>     - Compiled code should never terminate the R process within which it is running. Thus C/C++ calls to assert/abort/exit/std::terminate, Fortran calls to STOP and so on must be avoided. Nor may R code call q().
>     - A package must not tamper with the code already loaded into R: any attempt to change code in the standard and recommended packages which ship with R is prohibited. Altering the namespace of another package should only be done with the agreement of the maintainer of that package.
>     - **Packages should not write in the user’s home filespace (including clipboards), nor anywhere else on the file system apart from the R session’s temporary directory (or during installation in the location pointed to by TMPDIR: and such usage should be cleaned up). Installing into the system’s R installation (e.g., scripts to its bin directory) is not allowed.**
>
> Limited exceptions may be allowed in interactive sessions if the package obtains confirmation from the user.
>
> For R version 4.0 or later (hence a version dependency is required or only conditional use is possible), packages may store user-specific data, configuration and cache files in their respective user directories obtained from tools::R_user_dir(), provided that by default sizes are kept as small as possible and the contents are actively managed (including removing outdated material).
>     - Packages should not modify the global environment (user’s workspace).
>     - Packages should not start external software (such as PDF viewers or browsers) during examples or tests unless that specific instance of the software is explicitly closed afterwards.
>     - Packages should not send information about the R session to the maintainer’s or third-party sites without obtaining confirmation from the user.
>     - Packages must not disable the stack-checking mechanism in the R process into which they are loaded.
>     - CRAN packages should use only the public API. Hence they should not use entry points not declared as API in installed headers nor .Internal() nor .Call() etc calls to base packages. Also, ::: should not be used to access undocumented/internal objects in base packages (nor should other means of access be employed). Such usages can cause packages to break at any time, even in patched versions of R.
>     - Packages should not attempt to disable compiler diagnostics, nor to remove other diagnostic information such as symbols in shared objects.
>     - Security provisions must not be cicrumvented, for example by not verifying SSL certificates. 


A few potential approaches, expanding on your list:
1. Memoize to memory by default, provide message on package load or first `download_signal` use about how to cache to disk.
2. Memoize to temporary directory by default, with same message strategy.
3. Interactively ask user what to do on first use of `download_signal`, or stop with error message (?) on non-interactive use.

Going with 1. sounds good to me.

**Comment by brookslogan** [comment]
There still remains the messaging strategy: on package load vs. on first use of `download_signal` without manually doing something to indicate cache type preference.  Maybe `message`-ing on first default use is a little better, but I don't know if it's worth the implementation effort.

**Comment by sgsmob** [comment]
Can we close this?
