### ISSUE TITLE
Animate signals over time

### ISSUE THREAD

**Issue by chinandrew** [cmu-delphi/covidcast#46]
Given  a signal over multiple dates, return an animation (maybe using [matplotlib animation](https://matplotlib.org/3.1.1/api/animation_api.html))

**Comment by chinandrew** [comment]
So turns out this isn't super hard by just saving plots out and combining them into a gif. After pulling 30 days worth of data, it's 6 lines of code (5 if you don't use a temp dir) to generate a gif using the following code. Downside is it takes 3 minutes to run, as the plotting function isn't very optimized for this. e.g. it loads the shapefiles 30 times instead of having a plotting object load once on instantiation and then reusing it. MPL animation is a bit lower level which was more complicated to figure out.

Shouldn't be hard to wrap this into a method that just takes in a df and plotting args.
```
import covidcast
import datetime
import tempfile
import glob
from matplotlib import pyplot as plt
from PIL import Image

date_list = [datetime.date(2020,9,10) - datetime.timedelta(days=x) for x in range(30)][::-1]
df = covidcast.signal('fb-survey','smoothed_cli', start_day = min(date_list), end_day = max(date_list), geo_type = 'county') 

with tempfile.TemporaryDirectory() as tmpdirname:
    for d in date_list:
        covidcast.plot_choropleth(df, time_value=d) 
        plt.savefig(f"{tmpdirname}/{d}")
    img, *imgs = [Image.open(f) for f in sorted(glob.glob(f"{tmpdirname}/*"))]
    img.save(fp="animation.gif", format='GIF', append_images=imgs, save_all=True, duration=300, loop=0)
```

Not really sure why the text is so bold.


![animation](https://user-images.githubusercontent.com/20176218/93055147-534a0380-f61f-11ea-8756-3774008f1c00.gif)

**Comment by capnrefsmmat** [comment]
Yeah, I found MPL animation to be pretty difficult when I last used it a few years ago. I wonder if there have been improvements since.

The text seems to be ugly because there's no anti-aliasing, probably because GIFs only support 256 colors. Or maybe just because MPL doesn't do antialiasing on GIFs. We'll probably want to write to MP4 or WEBM, for embedding, although I dunno if that's possible through PIL.

I don't mind if it's a gross hack at first, since I think the first use case will be making a really cool blog post, and it's okay if the code is hard to run for other people for a bit...

**Comment by chinandrew** [comment]
After trial+erroring some file formats, compressions, and palates, the best combo for GIFs seems to be outputting JPGs and RGBA, but you still get weird artifacts for solid colors and on the colorbar.

Using imageio to write to mp4 gives better results and is still equally short code

```
writer = imageio.get_writer('animation.mp4', fps=3)
with tempfile.TemporaryDirectory() as tmpdirname:
    for d in date_list:
        covidcast.plot_choropleth(df, time_value=d) 
        plt.savefig(f"{tmpdirname}/{d}.jpg", format='jpg', dpi = 180)
        writer.append_data(imageio.imread(f"{tmpdirname}/{d}.jpg"))
writer.close()
```


screenshot
![Screenshot from 2020-09-15 02-03-19](https://user-images.githubusercontent.com/20176218/93190005-af805680-f6f7-11ea-9b43-3e7c52435ca7.png)


zipfile containing mp4 since github doesnt support mp4
[animation.mp4.zip](https://github.com/cmu-delphi/covidcast/files/5223756/animation.mp4.zip)
