### ISSUE TITLE
Add US territories to covidcast fips_to_abbr() etc.

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/covidcast#461]
The API now has data for the territories (Guam, Virgin Islands, Northern Marianas, American Samoa), at least for JHU. But these haven't made it into `covidcast::fips_to_abbr()`. This results in lots of `NA`'s in downstream processing that can potentially break things. (It broke the forecasting pipeline this weekend).

We're filtering them out for now, but we should update `covidcast`.

**Comment by capnrefsmmat** [comment]
See also #446

**Comment by chinandrew** [comment]
I completely missed that this was assign to me. I'll take a look at it next

**Comment by statsmaths** [comment]
I think this is also fixed on r-pkg-devel, and can be closed, right?
