### ISSUE TITLE
Create a lagged df function

### ISSUE THREAD

**Issue by sgsmob** [cmu-delphi/covidcast#477]
Add a function to `modeltools` that takes a `covidcast`-style data frame and a set of specified lags and converts it into a data frame with the added lagged columns.

**Comment by capnrefsmmat** [comment]
You mean like the `dt` argument to [`aggregate_signals`](https://cmu-delphi.github.io/covidcast/covidcastR/reference/aggregate_signals.html)?

**Comment by sgsmob** [comment]
Yes. although I think that `aggregate_signals` does not support a few important features:
- Operating on a data frame that is already in long or wide format (as opposed to the list of frames from a call to `covidcast_signals`
- Summing/averaging the signals in an epiweek.  For the forecasts, we want to predict the total number of cases/deaths/etc. that will occur in the next full epiweek.  From what I can tell, the closest functionality in `aggregate_signals` would be to aggregate into a wide df with a column for each day ahead in the epiweek, i.e., `value+1:cases`, value+2:cases`, ..., `value+7 cases`, which would then be summed in a separate step, after which the numerous value columns could be dropped.
