### ISSUE TITLE
Add tools to rearrange data for analysis

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#48]
For example, suppose I want to do a regression where I predict cases using various other signals. I need to obtain the signals, join them together, maybe lag some variables, and produce a data frame with one row per location and time, containing all measurements at that location/time.

We should provide a function, name to be determined, that

* takes a bunch of signal data frames
* joins them together and names the `value` columns after the signals
* optionally lags some variables, e.g. if I want to predict cases with lagged signals
* returns one big data frame

Then we should put a few examples in the package docs showing how we can use this to conduct a data analysis.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970461908005) by [Unito](https://www.unito.io/learn-more)

**Comment by ryantibs** [comment]
@chinandrew I'm sorry to ask because it's a bit lazy but ... can you point me to exactly where you implemented this in the Python package so I can see the naming and argument specifications you chose?

I already have similar functionality sitting around in some analyses/demo notebooks (like the [forecasting demo](https://delphi.cmu.edu/blog/2020/09/21/can-symptoms-surveys-improve-covid-19-forecasts/)), so it would be easy for me to add this to the R package.

**Comment by chinandrew** [comment]
This is in Python-packages/covidcast-py/covidcast.py in `aggregate_signals()` with documentation at the bottom of the first section here https://cmu-delphi.github.io/covidcast/covidcast-py/html/getting_started.html. 

We had a few discussions on the right interface (e.g. pandas has a multiindex DF) in #62, which might be Python specific but potentially worth a read (and you'll have to excuse my horrible late night writing). I don't think we ended up very opinionated about the implementations, so if you end up with good ideas let us know.

**Comment by capnrefsmmat** [comment]
Yeah, I think in R we should be able to do this with just `rbind` and `dplyr::pivot_wider` and a few extra steps to clean up the metadata and column names.

**Comment by chinandrew** [comment]
Closed by #156 , not sure why it didn't auto-close
