### ISSUE TITLE
Calibration plots do not facet on grouping variables

### ISSUE THREAD

**Issue by JedGrabman** [cmu-delphi/covidcast#486]
In `format_wedgeplot` (in `plot_calibration`), a user may specify `grp_vars`, `facet_rows` and `facet_cols`. If the user does specify  a value for `grp_vars`, but doesn't specify anything for `facet_rows` or `facet_cols`, it results in a rather confused plot, for example:

![Rplot](https://user-images.githubusercontent.com/7600154/110713485-057a1680-81d0-11eb-8559-f2fd3ee6dcbe.png)

I think the problem stems from `plot_calibration`. Previously, if a user specified grouping variables, it would [auto-determine the faceting](https://github.com/cmu-delphi/covidcast/blob/8a78de916bc0f0c83c9a22b710b5245d384a5380/R-packages/evalcast/R/plot_calibration.R). Now it does not.

Expected behavior:
If both faceting variables are NULL, attempt to auto determine faceting values
If a faceting variable is not null, check that the faceting is reasonable.

I think wedge plots can reasonably facet on 2 variables (one per row and column), while traditional plots can facet on 3 (color, row and column).

It might be a good idea to update `test_legal_faceting` (within `plot_coverage`) to take a maximum groups argument as well.

**Comment by JedGrabman** [comment]
@sarah-colq Can you take a look at this?

**Comment by sarah-colq** [comment]
@JedGrabman Do you remember what you specified for `grp_vars` here?

**Comment by JedGrabman** [comment]
I think I was using 
grp_vars = c("ahead")
avg_vars = c("geo_value", "forecast_date")
on a predictions_card.

**Comment by sarah-colq** [comment]
So in changes have been made since then, where there are not default values for facet_rows and facet_cols for each type of plot (which was the behavior we specified before).  Then it fails on test_legal_faceting.   @dajmcdon do we still want default values for the calibration plots?

**Comment by sarah-colq** [comment]
Okay after discussion with @JedGrabman we have decided on hardcoded values for each calibration plot type and improve the test_legal_faceting error message.
