### ISSUE TITLE
 Add tools to Python client to rearrange data for analysis 

### ISSUE THREAD

**Issue by chinandrew** [cmu-delphi/covidcast#50]
Python package version of #48
For example, suppose I want to do a regression where I predict cases using various other signals. I need to obtain the signals, join them together, maybe lag some variables, and produce a data frame with one row per location and time, containing all measurements at that location/time.

We should provide a function, name to be determined, that

    takes a bunch of signal data frames
    joins them together and names the value columns after the signals
    optionally lags some variables, e.g. if I want to predict cases with lagged signals
    returns one big data frame

Then we should put a few examples in the package docs showing how we can use this to conduct a data analysis.

**Comment by chinandrew** [comment]
Just to make sure I'm getting this right, is this the intended behaviour?

df1:
```
geo_val,time,value,signal
a,20200101,2,smoothed_cli
b,20200101,4,smoothed_cli
c,20200101,6,smoothed_cli
a,20200102,8,smoothed_cli
```
df2:
```
geo_val,time,value,signal
a,20200101,1,smoothed_adj_cli
b,20200101,3,smoothed_adj_cli
c,20200101,5,smoothed_adj_cli
d,20200101,7,smoothed_adj_cli
```
df3:
```
geo_val,time,value,signal
b,20200101,0.5,raw_cli
c,20200101,1.5,raw_cli
d,20200101,2.5,raw_cli
b,20200102,3.5,raw_cli
```

```
to_be_named_function([df1 ,df2, df3], lags = [0, 0 , 1])
> geo_val,time,smoothed_cli,smoothed_adj_cli,raw_cli
  a,20200101,2,1,NULL
  b,20200101,4,3,NULL
  c,20200101,6,5,NULL
  b,20200102,NULL,NULL,0.5
  a,20200102,8,NULL,NULL
  c,20200102,NULL,NULL,1.5
  d,20200102,NULL,NULL,2.5
  b,20200103,NULL,NULL,3.5
```
Other thoughts on implementation:
- Outer join would retain all rows, which I assume gives most flexibility by default? Could offer an inner join arg as well.
- Order by time and then geo value, just like how signal() currently returns things
- Accept duplicate signals (?), and just have to adjust col names as needed (though pandas might give us some of this for free since it already adds _x, _y to columns if you join two tables with duplicate cols). Do we want to support multiple data sources? If so, would also need to add that to the column name
- Lag = 1 means shift that signal a day forward or a day backwards? e.g. Jan 5th becomes Jan 6th or Jan 4th? I do the former in my example (so 1 lag means 20200101 becomes 20200102), but I vaguely recall this might be wrong.
- For function interface, could also do tuples of (df,lag) instead of separate df and lag lists/tuples/etc, but then if you don't care about lags you need to specify 0 for all of them. Open to other interface ideas as well
- `lag` as a column in the signal df (for the reporting lag) vs the lag here may be a bit confusing for users

**Comment by capnrefsmmat** [comment]
Yes, I think that's exactly right. Your lag behavior matches how [covidcast_cor() behaves](https://cmu-delphi.github.io/covidcast/covidcastR/reference/covidcast_cor.html), and to your point about reusing the word "lag", you could use "dt" like it does.

Accounting for multiple data sources is an issue, since we have signals with the same name reported by different data sources. We could do something like `fb-survey.raw_cli` (`source.signal`); what separators work well in Pandas without making your column access syntax contorted?

**Comment by chinandrew** [comment]
> Yes, I think that's exactly right. Your lag behavior matches how [covidcast_cor() behaves](https://cmu-delphi.github.io/covidcast/covidcastR/reference/covidcast_cor.html), and to your point about reusing the word "lag", you could use "dt" like it does.
Cool, thanks.

> Accounting for multiple data sources is an issue, since we have signals with the same name reported by different data sources. We could do something like `fb-survey.raw_cli` (`source.signal`); what separators work well in Pandas without making your column access syntax contorted?

For now I'm appending the source and signal to the column names, separated by underscores. Opened PR #62 with examples
