### ISSUE TITLE
Error in utils::download.file

### ISSUE THREAD

**Issue by kenneth-lee-ch** [cmu-delphi/covidcast#522]
**Issues**
I tried to download the covidcast package by following this [documentation](https://cmu-delphi.github.io/covidcast/covidcastR/articles/covidcast.html), but it throws an error. My R version: 4.0.4

**Code I used:**
devtools::install_github("cmu-delphi/covidcast", ref = "main", subdir = "R-packages/covidcast")

**Error message:**
Downloading GitHub repo cmu-delphi/covidcast@main
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/cmu-delphi/covidcast/tarball/main' failed

**Comment by capnrefsmmat** [comment]
Can you try opening the link https://api.github.com/repos/cmu-delphi/covidcast/tarball/main in your web browser and timing how long it takes to download?

It's a big file (257 MB), and if it takes longer than 60 seconds, `download.file` would time out and stop.

**Comment by kenneth-lee-ch** [comment]
Indeed, it took more than 60 seconds. Thanks!

**Comment by rkclement** [comment]
I'm also having this error, though when I try the link that @capnrefsmmat pointed out, it doesn't take longer than 60 seconds... 

But now that I have that file downloaded, can I just install the package using that?

**Comment by kenneth-lee-ch** [comment]
@rkclement  yes, I just installed covidcast portion only inside the file.

**Comment by capnrefsmmat** [comment]
Yes, I think downloading the repository, going to the `R-packages/covidcast/` directory, and running `devtools::install()` should be sufficient.

**Comment by rkclement** [comment]
Thanks, that worked well.
