### ISSUE TITLE
Run R covidcast CI on R 4.1 as well

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#538]
Currently the testthat tests in `test-plot.R` contain

```r
skip_if( (R.Version()$major != "4") )
```

because R's SVG output changed slightly from 3.6 to 4 in ways that make the testthat tests fail. But we only run CI on R 3.6. We should add R 4.0.

For practicality we might need to fix #277 so that two CI runs don't take ages.

**Comment by dshemetov** [comment]
Closed by #620
