### ISSUE TITLE
Simplified county shapes are a bit too simplified

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#542]
In #500 we created simplified versions of the map shapefiles to reduce the size of the package. However, we appear to have simplified county shapes a bit too much. For example,

```r
covidcast_signal("doctor-visits", "smoothed_cli", "2021-03-01", "2021-03-01") %>% plot(plot_type="choro", include="mi")
```

![Screen Shot 2021-05-05 at 3 23 36 PM](https://user-images.githubusercontent.com/711629/117197474-dd64f900-adb5-11eb-8be7-2f9b1acd797f.png)

I'm pretty sure [Huron County](https://www.google.com/maps/place/Huron+County,+MI/@43.9138745,-84.0506141,8z/data=!3m1!4b1!4m5!3m4!1s0x8826fb1adc107517:0xf2a537f92de61261!8m2!3d43.9466791!4d-82.820974) is supposed to go all the way to the shoreline of the "thumb", rather than being turned into a trapezoid. The other counties also don't seem to fit correctly.

We might need to try a couple varieties of the parameters to get county shapes that are acceptable without huge files.

@statsmaths Do you know how the simplification parameters work to try tuning them?

**Comment by statsmaths** [comment]
The file to create the reduced GeoJSON files is in the repository and the parameter to change is called `dTolerance`: 

https://github.com/cmu-delphi/covidcast/blob/30e9917839a3778e78ecffb3098721c368a6dfd4/R-packages/data-raw/create_geojson.R#L22-L24

A smaller number produces less simplification. The units are in the coordinate projection, so there's no particular rule-of-thumb. I think I used this one because it looked good at the national level, but clearly it breaks down on a single state.

**Comment by capnrefsmmat** [comment]
Hmmm, if those are in coordinate projection units, [then they're in meters](https://epsg.io/5070), and that's 10km. The `dTolerance` parameter isn't really documented, but if it's a tolerance of 10km for changes in the shape after simplification, that would explain the issue.

Looking at [section 5.2.1 here](https://geocompr.robinlovelace.net/geometric-operations.html), I wonder if we want to use `rmapshaper::ms_simplify`, because it apparently uses an algorithm designed to simplify groups of shapes at once without introducing gaps or overlaps between them.

**Comment by statsmaths** [comment]
That's a great suggestion. I wasn't aware of the rmapshaper package, but it works really well. Confusingly, st_simplify has a preserve topoogy parameter but it does not actually preserve topology in that sense (?).

Here is what I get with their default settings (file sizes are only marginally larger). How does that look to you? I can check it into the r-pkg-devel branch once we get the tuning parameter figured out.

![michigan](https://user-images.githubusercontent.com/5752184/117349130-0ac6ab00-ae79-11eb-8647-e33bb00ed597.png)

**Comment by capnrefsmmat** [comment]
That looks *much* nicer. Looking at [a different map of Michigan](https://geology.com/county-map/michigan.shtml), you can tell the counties are somewhat simplified, but everything is still recognizable and the weird gaps are gone. I'd call that close enough, given that our goal is making simple choropleths, not building a general-purpose mapping system.

**Comment by statsmaths** [comment]
Yes, that's a great package that you found. I will be using it in the future for simplifying multiple polygons at the same time.

New files and an updated script are now pushed into r-pkg-devel
