### ISSUE TITLE
Provide functions to look up FIPS codes, CBSA IDs, etc.

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#55]
As of #29, the R package now has functions `fips_to_name`, `name_to_fips`, etc. for working with FIPS codes and CBSA IDs. See [the documentation](https://cmu-delphi.github.io/covidcast/covidcastR/reference/name_to_fips.html).

This would be very handy for the Python package, because it's pretty inconvenient to have to figure out the right code for a county or MSA to be able to query data for it. I suspect the Python versions can work very similarly to the R versions, using the Census shapefiles (or other Census data, such as the Census data frames produced for the R package) to get names and IDs.

**Comment by chinandrew** [comment]
Seems reasonable to do, though I wonder if this is something that would fit well into the geomapping stuff that @jsharpna and @dshemetov are working on. James and I have briefly talked about splitting it into it's own package, but given that that's in a separate repo for now I don't want to upscope the work there. For now I can implement this in a fairly lightweight fashion in this repo and we can discuss pulling it out at a later time if needed.

**Comment by capnrefsmmat** [comment]
Yeah, it's easy to do in a lightweight way for just looking up names and such (the R package just keeps a few data tables to search). But integrating the geomapper would be interesting, because then you could, say, ask what counties are included in an MSA or what data fits into a certain HRR, and do your own custom aggregating. Perhaps a longer-term extension.

**Comment by dshemetov** [comment]
This seems feasible to me.
