### ISSUE TITLE
doctor-visits smoothed_adj_cli 20210330 gives "no results" response

### ISSUE THREAD

**Issue by lematt1991** [cmu-delphi/covidcast#553]
I'm currently getting `{'result': -2, 'message': 'no results'}` response from the following code:

```python
from delphi_epidata import Epidata
res = Epidata.covidcast("doctor-visits", "smoothed_adj_cli", "day", "state", ["20210330"], "*")
print(res)
```

This works fine if I use "county" instead of "state".  Is this a bug or is this data known to be missing?  It seems that it is only this particular date that is missing for me.  Any help is much appreciated, thanks!

**Comment by krivard** [comment]
Oh very weird, looks like something in the database wiped out one of our versioning flags. The data are all there, just not annotated properly. The current fix we have for this is slow, but in the meantime it's possible to retrieve that day's data using an issue query:

```
>> from delphi_epidata import Epidata
>> Epidata.covidcast("doctor-visits", "smoothed_adj_cli", "day", "state", ["20210330"], "*",issues="20210611")
>> print(len(res["epidata"]))
53
```

We currently only publish 70 days of backfill for doctor-visits (so the earliest day published today was April 19) -- so the query above should be safe until the next bugfix.

**Comment by lematt1991** [comment]
Awesome, thanks for the quick response @krivard!
