### ISSUE TITLE
Missing covidcast data for all counties but those in California for vaccine acceptance survey

### ISSUE THREAD

**Issue by lcoome** [cmu-delphi/covidcast#554]
Currently it appears that all data for states except California are missing for the vaccine acceptance survey. Is this a data issue that will be resolved soon?

This is the code/signal I'm currently using:

`vacc_accept = covidcast_signal("fb-survey", "smoothed_covid_vaccinated_or_accept", start_day = "2021-01-01",
                             end_day = Sys.Date(),
                             geo_type = "county")`

**Comment by krivard** [comment]
Hi, that signal was discontinued as of Wave 11, May 19 2021. For more details on signals you might use as a replacement, see [the API documentation for this source](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/fb-survey.html#vaccination-indicators).
