### ISSUE TITLE
404 error when fetching data

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#556]
I'm getting the following error:

```
> library(covidcast)
> dat <- covidcast_signals(data_source = "safegraph",
+                          signal = c("restaurants_visit_prop",
+                                     "completely_home_prop"),
+                          start_day = "2020-08-01",
+                          end_day = "2020-09-01",
+                          geo_type = "county")
Error in .request(list(source = "covidcast_meta", format = "csv")) : 
  Not Found (HTTP 404). Failed to fetch data from API.
```

However, when I change `"county"` to `"state"` in the above, it works.

**Comment by krivard** [comment]
As far as we can tell, the 404 behavior is not linked to geo type, but some problem in the API server load balancing system. Investigation ongoing.

**Comment by krivard** [comment]
We've applied the "turn everything off, then on again" solution, which is never very satisfying, but (1) it seems to have resolved the latency problems, and (2) the indicators that failed last night with 404s are now running successfully. 

When you get a minute, see if it's working now for you as well.

**Comment by jacobbien** [comment]
Haha, great solution!  Just tried it and can confirm that it's working.  Thanks!
