### ISSUE TITLE
Varying lag in issue date of jhu-csse data

### ISSUE THREAD

**Issue by nbanho** [cmu-delphi/covidcast#575]
First, thanks a lot for this great package, which makes it very easy to generate "honest" data. I have an issue/question related to the delay in the JHU data (as_of / issue date). 

I thought that the data from _jhu_csse_ were available without delay, yet for some dates, e.g. _2020-06-24_ , the data is issued two days later (confirm from query below). Is this no bug in the query? My assumption was that the JHU data were always available in real-time, i.e. on the same day.

`covidcast_signals(data_source = rep("jhu-csse", 2),
                      signal = c("confirmed_incidence_num", "confirmed_incidence_prop"),
                      geo_type = "state",
                      start_day = as.Date("2020-06-24") - 60,
                      end_day = as.Date("2020-06-24"),
                      as_of = as.Date("2020-06-24"))`

(even if you set the `as_of` date to "2020-06-25", the latest available date is still "2020-06-23")

**Comment by krivard** [comment]
Hello! Thanks for your interest.

We get our data directly from JHU-CSSE's github repository of cases & deaths timeseries data ([cases](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv); [deaths](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv)). JHU updates this file sometimes multiple times a day. Updates made at the end of a day may contain early estimates for that same day, but this is not typical. Our pipeline is currently scheduled to run once each day at 4AM US/New_York time to accommodate the CDC Forecast Hub submission deadline, but it has been scheduled for different times throughout the pandemic as conditions changed. Depending on how our pipeline time lines up with CSSE's updates, we generally expect a lag of 1 day for this source. For example, the latest commit to that file as I'm typing this on 2022-01-11 10:30AM was made 5 minutes ago, and the maximum date in the file is 2022-01-10. The commit active at 4AM this morning was made at 2022-01-10 11:51PM, and also has a max date of 2022-01-10, so the covidcast issue for today has a lag of 1.

From [the commit history](https://github.com/CSSEGISandData/COVID-19/commits/master?before=b08e987bd37c03a25374cfc4f1b87c6438c7c195+1050&branch=master&path%5B%5D=csse_covid_19_data&path%5B%5D=csse_covid_19_time_series&path%5B%5D=time_series_covid19_confirmed_US.csv) in late June 2020 it looks like in addition to the daily automated uploads, there were manual commits made to the cases file on both June 24 and 25, and at least one of those fixed a formatting problem which would have crashed our pipeline.

2020-06-25 is the only issue date in June or July 2020 for which there is 2 days of lag -- so I think you just got unlucky here. 1 day is typical.

**Comment by nbanho** [comment]
Thank you so much for your help and looking carefully into this!
Just a small follow-up question regarding the lag, to make sure, that I am setting my pipeline up correctly. If I set the `as_of` date to e.g. "2020-10-10", then I will typically have daily cases up until "2020-10-09". But since your pipeline runs at 4AM, then it would still make sense to forecast cases for "2020-10-10" (assuming that I would make the forecast at 4AM), right? Background: I am doing a retrospective forecasting evaluation and I want to make sure whether the first timely and honest forecast I can make is for the same day "2020-10-10" or one day later "2010-10-11".

**Comment by krivard** [comment]
Suppose you're trying to evaluate forecaster performance where forecasters are run on day X to predict day Y. Your evaluation should use X for the as-of date when building the dataset to give to the forecaster. The relationship between X and Y depends entirely on the forecasting scenario you're trying to evaluate. It is perfectly honest to predict for a Y < X if you're working on a scenario about data reporting delays ("can we predict on day X what _will eventually be reported_ about a day in the past Y?). However, if your scenario is to predict what will happen in the future, then your evaluation should use Y>X.

For example, the current hospital admissions forecasting challenge hosted by the COVID-19 Forecasting Hub requires weekly forecasts for 1, 2, 3, and 4 weeks after the forecast date (=the day the forecasters are run and the forecasts are submitted). To evaluate a forecaster in this scenario, you would use as-of=X and predict for Y=X+7 days, X+14 days, X+21 days, etc. 

You would then compare the forecaster output with a dataset constructed using as-of=Z, where Z is either imposed by the scenario ("what do we mean by 'eventually'") or =today (which is the best approximation available for "when all the data is in and this is all over").

Does that make sense?

**Comment by nbanho** [comment]
Yes, make sense! Thanks for the detailed explanation.
