### ISSUE TITLE
Python covidcast client `test_plotting` is failing

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/covidcast#596]
The error is

```python
        # test w/ megacounty combine
        mega = plotting._join_county_geo_df(test_input, "county_code", geo_info, "left", True)
        expected_mega = gpd.read_file(
            os.path.join(CURRENT_PATH,
                         "reference_data/expected__join_county_geo_df_mega.gpkg"),
            dtype={"geo_value": str})
>       pd.testing.assert_frame_equal(expected_mega, mega)

E   AssertionError: ExtensionArray are different
E   
E   ExtensionArray values are different (33.33333 %)
E   [index]: [0, 1, 2]
E   [left]:  [POLYGON ((-76.71131299999999 39.371933, -76.626193 39.37201 ...
E   [right]: [POLYGON ((-76.71131299999999 39.371933, -76.626193 39.372017 ,...
```

I'm trying different pairings of [`geopandas`](https://pypi.org/project/geopandas/#history) and [`shapely`](https://pypi.org/project/Shapely/#history) versions, dated around the time that Alex and Andrew were working on the Python package (and the build was working) and I'm still getting the error. 
- if I try `shapely<1.8.0` with `geopandas>=0.7.0`, I get `E       NotImplementedError: A polygon does not itself provide the array interface. Its rings do.`
- if I do `shapely>=1.8.0` with `geopandas>=0.7.0`, I get `E   AssertionError: ExtensionArray are different`

_Originally posted by @dshemetov in https://github.com/cmu-delphi/covidcast/issues/592#issuecomment-1259892430_

Nothing changed in the Python client files in over a year. So the issue _should_ be in the moving dependencies, but I wasn't able to fix it by digging in that direction. Old CI run logs have been deleted, so we don't have a record of the exact dependency versions that passed these tests.

**Comment by brookslogan** [comment]
Migrating from Slack:
* @dshemetov noted similarity to a problem we had in R packages due to BLAS implementations giving different values for PR rotation, which we addressed by not rotating PR.
* Python package still has PR rotation code [here](https://github.com/cmu-delphi/covidcast/blob/13c9c8b52f1729f84c24e3b6cfac04db20423086/Python-packages/covidcast-py/covidcast/plotting.py#L327).
* @krivard is taking a look.

**Comment by krivard** [comment]
Hmmm on checking actual output against expected, it looks instead like it's a color scale problem: 

[test_plots_expected_actual.pdf](https://github.com/cmu-delphi/covidcast/files/11082319/test_plots_expected_actual.pdf)
