### ISSUE TITLE
Cannot get signal data at county level for 'smoothed_wbelief_masking_effective'

### ISSUE THREAD

**Issue by pirolli** [cmu-delphi/covidcast#600]
Call:
cc_masking_effective=covidcast.signal('fb_survey', 'smoothed_wbelief_masking_effective')

Error message:
'Unable to find metadata for source 'fb_survey', signal 'smoothed_wbelief_masking_effective', at 'county' resolution.'

**Comment by capnrefsmmat** [comment]
This is probably because the data source name is `fb-survey`, rather than `fb_survey`. For some reason we use hyphens in data sources and underscores in signals. This should work:

```python
cc_masking_effective = covidcast.signal('fb-survey', 'smoothed_wbelief_masking_effective')
```

**Comment by pirolli** [comment]
Hah! That was it.

Thanks for the quick response.
