### ISSUE TITLE
Add flexible warning option for production pipeline in the R package

### ISSUE THREAD

**Issue by bnaras** [cmu-delphi/covidcast#63]
The upstream data generation pipeline relies on accurate warnings to detect anomalies. Currently, if the process generates warning, I have to explicitly request to see the warnings at the end of the run.  It would really help to send the warnings to a logger as they happen.

The code below, which can be placed in `covidcast/R/zzz.R` as is, allows a user to set an option `covidcast.warning`. If not set, it falls back to the standard `base::warning`. In addition, each call to `warning("bad", "stuff", ...)` has to be replaced with `getOption("covidcast.warning")("bad", "stuff", ...)`, which is a simple search and replace.  Example below. Happy to provide a PR if needed.

## File `zzz.R`
```{r}
## Set up flexible logging options on load
.onLoad <- function(libname, pkgname) {
    opts <- options()
    opts.covidcast <- list(
        ## Default warning function is the base warning function
        covidcast.warning = base::warning
    )
    toset <- !(names(opts.covidcast) %in% names(opts))
    if (any(toset)) {
        options(opts.covidcast[toset])
    }

    invisible()
}
```
## Example

```{r}
> library(covidcast)
We encourage COVIDcast API users to register on our mailing list:
https://lists.andrew.cmu.edu/mailman/listinfo/delphi-covidcast-api
We'll send announcements about new data sources, package updates,
server maintenance, and new features.
> m  <- covidcast_signal("fb-survey", "raw_cli", geo_type = "msa",
                  geo_values = name_to_cbsa("Pittsburgh"))

Fetched day 20200406: 1, success, num_entries = 1
...
Fetched day 20200901: 1, success, num_entries = 1
Warning message:
In single_geo(data_source, signal, start_day, end_day, geo_type,  :
  Fetching raw_cli from fb-survey for 20200412 in geography '38300': no results
```

Now set option.

```{r}
 options(covidcast.warning=logger::log_warn)
> m  <- covidcast_signal("fb-survey", "raw_cli", geo_type = "msa",
                  geo_values = name_to_cbsa("Pittsburgh"))
Fetched day 20200406: 1, success, num_entries = 1
Fetched day 20200407: 1, success, num_entries = 1
Fetched day 20200408: 1, success, num_entries = 1
Fetched day 20200409: 1, success, num_entries = 1
Fetched day 20200410: 1, success, num_entries = 1
Fetched day 20200411: 1, success, num_entries = 1

WARN [2020-09-03 15:31:06] Fetching raw_cli from fb-survey for 20200412 in geography '38300': no results
Fetched day 20200413: 1, success, num_entries = 1
...
```

**Comment by capnrefsmmat** [comment]
This is an interesting approach. But couldn't you use `withCallingHandlers` to do this as well? For example,

```r
withCallingHandlers({
    m  <- covidcast_signal("fb-survey", "raw_cli", geo_type = "msa",
                           geo_values = name_to_cbsa("Pittsburgh"))
    },
    warning = function(c) { 
        logger::log_warn(conditionMessage(c))
    }
)
```

Ideally we could raise a condition with a class more specific than `warning` so you can choose which warnings to log and how to log them. If we do that, this becomes a great use case for the condition system.

**Comment by bnaras** [comment]
Signaling a condition gives the most flexibility, for then I could selectively look at things I want to see. So if you are planning to implement that disregard my comment.  I can then write handlers for what I want to focus upon. Otherwise, I'd be looking at all warnings, not all of which are harmful...
