### ISSUE TITLE
Check if covidcast vignettes will fail once API rate limits are enabled

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#633]
It's hard to count how many API calls are made when building the covidcast R package. We should set the package to use the staging server (with rate limits turned on), then try a full `devtools::check(remote = TRUE)` to see if all vignettes can be built and all checks done without hitting the limit.

If we do hit the limit, we'll need to make a documentation update to avoid this, as CRAN automatically rebuilds packages periodically and will complain if the vignettes fail to build.

(There's also a worst-case option where CRAN runs checks repeatedly in a short period, or under multiple configurations, with the same IP address; but we won't know if that occurs until it happens.)

**Comment by krivard** [comment]
I can take a look today.

**Comment by krivard** [comment]
The vignettes include 16 calls to `covidcast_signal[s]`. Through a straight swap I switched 11 of them to signals exempt from rate limits. The remaining 5 calls are

* indicator-combination nmf signals, used as a primary example in plotting-signals.Rmd (x3)
* jhu-csse cumulative case data, used to contrast with incidence data in plotting-signals.Rmd and correlation-utils.Rmd (x2)

A single run of `devtools::check(remote = TRUE)` succeeds; a second one in the same clock hour fails with a rate limit message. 

In case that is all we need, I'll open a PR with these changes.

In case that's not enough, I'll start a rewrite of the text & discussion to replace nmf with something else. Candidates:

* google-symptoms - good coverage, might not stay active, different from cases/deaths/outpatient data used elsewhere in the vignettes
* chng - okay coverage, likely to stay active, doubles up on outpatient data used elsewhere
* quidel - low coverage, likely to stay active, different from data used elsewhere
