### ISSUE TITLE
Dplyr::mutate Error, signals are not loading 

### ISSUE THREAD

**Issue by kruelas** [cmu-delphi/covidcast#637]
I am using R and signals that use to work a few hours earlier no longer work. I get this filtering error:

> mask.ds <- covidcast_signal(data_source = "fb-survey", signal = "smoothed_wwearing_mask", geo_type = "state", time_type ="day")
Error in `dplyr::mutate()`:
ℹ In argument: `min_time = adjust_dates(.data$min_time, .data$time_type)`.
Caused by error in `purrr::map2()`:
ℹ In index: 1.
Caused by error in `match.arg()`:
! 'arg' should be one of “day”, “week”
Backtrace:
  1. covidcast::covidcast_signal(...)
 12. covidcast (local) adjust_dates(.data$min_time, .data$time_type)
 14. purrr::map2(col, time_type, api_to_date)
 15. purrr:::map2_("list", .x, .y, .f, ..., .progress = .progress)
 19. covidcast (local) .f(.x[[i]], .y[[i]], ...)
 20. base::match.arg(time_type)
 21. base::stop(...)

This use to work and no longer does.  I deleted the packages I was using, reinstalled them, and ran the following code but to no avail:

library(conflicted)

conflicted::conflict_prefer("map2", "purrr")  # Prioritize map2 from purrr package
conflicted::conflict_prefer("filter", "dplyr")  # Prioritize filter from dplyr package

# Loading other packages
library(sjPlot)
library(lubridate)
library(ghibli)
library(dplyr)
library(tidyverse)
library(covidcast)

**Comment by kruelas** [comment]
Saw the requiring of API key in the post below

**Comment by capnrefsmmat** [comment]
Yes, this will happen fore requests that exceed the API usage limits until next week, when they'll get an HTTP 429 error response. For anyone Googling this error message to figure out what to do, see here: https://github.com/cmu-delphi/delphi-epidata/issues/1183
