### ISSUE TITLE
get_covidhub_forecast_dates("CMU-TimeSeries") throws an as_date error

### ISSUE THREAD

**Issue by zterner-mitre** [cmu-delphi/covidcast#639]
I am trying to follow the tutorial here (https://cmu-delphi.github.io/covidcast/evalcastR/articles/evalcast.html) to set up an evaluation pipeline for some forecasts that are being generated using the CDC forecasting hub format. The `lubridate` package seems to be throwing an issue when `get_covidhub_forecast_dates("CMU-TimeSeries")` is called.

<img width="766" alt="image" src="https://github.com/cmu-delphi/covidcast/assets/117375468/86afb852-e20a-4a2f-a8e5-572ef5106808">

Is there a missing step, or an easy way to fix this function to let get_covidhub_forecast_dates work?

**Comment by zterner-mitre** [comment]
If I define `forecast_dates_dec <- seq(ymd('2020-12-01'), ymd('2020-12-31'), by='1 day')` and try to define `predictions_cards_ens` and `predictions_cards_cmu` in the next lines, I get the same issue.

<img width="764" alt="image" src="https://github.com/cmu-delphi/covidcast/assets/117375468/c6625b63-462b-44a8-95ca-6783657d78a8">

**Comment by zterner-mitre** [comment]
Hi, I am using evalcast 0.3.0. I tried installing evalcast yesterday, but encountered this issue:

***@***.***

Later I found that evalcast had been installed, so I thought perhaps it was installed with covidcast? I’d be happy to update to 0.3.1 but not sure how to best do that.

Thanks,
Zach

--
Zachary Terner, Ph.D

From: Dmitry Shemetov ***@***.***>
Date: Friday, June 23, 2023 at 11:58 AM
To: cmu-delphi/covidcast ***@***.***>
Cc: Dr. Zach Terner ***@***.***>, Author ***@***.***>
Subject: [EXT] Re: [cmu-delphi/covidcast] get_covidhub_forecast_dates("CMU-TimeSeries") throws an as_date error (Issue #639)
Hi thanks for the report! What is your evalcast version? I'm not able to reproduce this on evalcast_0. 3. 1. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message


Hi thanks for the report! What is your evalcast version? I'm not able to reproduce this on evalcast_0.3.1.

**Comment by zterner-mitre** [comment]
Did you receive the screenshot I sent? It contained the following text

remotes::install_github("cmu-delphi/covidcast", ref = "main",
+                         subdir = "R-packages/evalcast")
Downloading GitHub repo ***@***.***
Error: Failed to install 'covidcast' from GitHub:
  Unknown remote type: bettermc=github
  object 'bettermc=github_remote' of mode 'function' was not found

--
Zachary Terner, Ph.D

From: Dmitry Shemetov ***@***.***>
Date: Friday, June 23, 2023 at 12:21 PM
To: cmu-delphi/covidcast ***@***.***>
Cc: Dr. Zach Terner ***@***.***>, Author ***@***.***>
Subject: [EXT] Re: [cmu-delphi/covidcast] get_covidhub_forecast_dates("CMU-TimeSeries") throws an as_date error (Issue #639)
Hm your error seems to be truncated (maybe an email formatting issue?). One of my colleagues is also running into installation issues, I'm happy to help debug. — Reply to this email directly, view it on GitHub, or unsubscribe. You are


Hm your error seems to be truncated (maybe an email formatting issue?).

One of my colleagues is also running into installation issues, I'm happy to help debug.

**Comment by dshemetov** [comment]
The screenshot didn't come through unfortunately. Thank you for the text though. Can you try:

```R
install.packages("pak")
pak::pkg_install("cmu-delphi/covidcast/R-packages/evalcast")
```

**Comment by zterner-mitre** [comment]
Thanks! That helped. Also didn't realize that the emails I was getting were posts from here -- sorry about the image formatting issues.

This issue is resolved on my end, as the tutorial runs all the way until `plot_calibration` gives two different errors of "Can't subset `.data` outside of a data mask context." based on which plot_calibration is run. Should that be in a different issue or also included here?

**Comment by dshemetov** [comment]
Glad that worked! And sure, let's handle that in another issue.

**Comment by zterner-mitre** [comment]
This issue of the dates has mysteriously come back -- did this happen as a result of the package getting updated? 
<img width="785" alt="image" src="https://github.com/cmu-delphi/covidcast/assets/117375468/f85edc3c-2166-4768-a64e-c096d2f3bdef">

(It also happens using get_covidhub_predictions, as specified in my second comment)

I encountered this issue and updated the evalcast package using pak::pkg_install("cmu-delphi/covidcast/R-packages/evalcast"), but that didn't resolve the issue :(
