### ISSUE TITLE
Issue 639 (get_forecast_dates) is showing previous issues 

### ISSUE THREAD

**Issue by zterner-mitre** [cmu-delphi/covidcast#646]
The issue presented here https://github.com/cmu-delphi/covidcast/issues/639 has come back. Maybe this happened as a result of the package getting updated?

![image](https://github.com/cmu-delphi/covidcast/assets/117375468/28002e07-d97b-4010-8613-7ae0752447af)

(It also happens using get_covidhub_predictions, as specified in my second comment in that thread)

To resolve this issue, I updated the evalcast package using pak::pkg_install("cmu-delphi/covidcast/R-packages/evalcast") as instructed last time, but that didn't resolve the issue :(

PS - I commented at the end of the previous issue, but wasn't sure that would notify you, so I thought it might help to start the issue again here.

**Comment by dshemetov** [comment]
Thanks for the report! Strange that the bug appeared, disappeared, and now reappeared. My guess is this broke because GitHub changed its layout, while the code to get the dates parsed the html. I made a fix that uses GitHub API instead. Hopefully we can get it merged soon.

**Comment by dshemetov** [comment]
@zterner-mitre please try installing the package again and let me know if you are still having issues!
