### ISSUE TITLE
WIS numbers look wrong for cumulative deaths; CovidHub forecasts are identical

### ISSUE THREAD

**Issue by zterner-mitre** [cmu-delphi/covidcast#655]
Hi,

I am not sure this merits an issue, but I wanted to ask if the results I am getting are correct, since they _seem off_ without further explanation. In particular, there are a few things I have been noticing:

1. The WIS numbers for cumulative deaths as given by CDC ensembles seem very high for summer 2021. The "baseliner" gives more reasonable results, and in general, other forecasts give much more reasonable results. I omitted other forecastsfrom this plot since I was using IHME-CurveFit, which gives poor results and takes a very long time to download due to all their forecasts, but other forecasters do seem to perform better in cumulative deaths. (I also wanted to use one of the UChicago forecasts, but it does not seem to have this data available then.)
[Issues File - Timepoint2 - CDC - Cumulative Deaths Comparisons.pdf](https://github.com/cmu-delphi/covidcast/files/12345114/Issues.File.-.Timepoint2.-.CDC.-.Cumulative.Deaths.Comparisons.pdf)

2. At least two of the CovidHub ensembles give exactly the same forecasts and error metrics. This is apparent both in the attached PDF, since the two ensembles are colinear, and in this screenshot, where all the error metrics are the same.
![image](https://github.com/cmu-delphi/covidcast/assets/117375468/1bdf0bf3-fbec-49df-8fbf-5697afbe0859)

I am also attaching R code with a reproducible example, but I saved it as a .txt file since Github wouldn't let me upload an R file.
[reproducible-ex-evalcast-github-as-txt.txt](https://github.com/cmu-delphi/covidcast/files/12345147/reproducible-ex-evalcast-github-as-txt.txt)

My questions here are:
1. Is the WIS calculation correct for cumulative deaths? Or are there some issues with how these ensembles are created, and the fact that they have high WIS is correct? In particular, the cumulative deaths WIS seem here are much higher than the incident deaths one can see on the Delphi dashboard. Is that a function of things being cumulative, or something else?
2. Should these CDC ensembles have the exact same forecasts and errors?

**Comment by nmdefries** [comment]
Thanks for reaching out.

The [raw data files](https://github.com/reichlab/covid19-forecast-hub/tree/master/data-processed) for `COVIDhub_CDC-ensemble` and `COVIDhub-4_week_ensemble` predictions match exactly until Nov 2021, after which hospitalization predictions match exactly but death predictions differ. (The CDC ensemble stopped predicting cases in Dec 2021.) So the matching error metrics for these target dates are correct.

I don't know if or why these models were supposed to match exactly; I'm looking into that more.

Delphi's [forecast evaluation dashboard](https://delphi.cmu.edu/forecast-eval/) uses _incident_ deaths, not cumulative deaths. If I use your script but set `signal.var = "deaths_incidence_num"` instead and use `signal.var` when calling `get_covidhub_predictions`, the WIS values in the `scorecards` object exactly match those shown in Delphi's forecast evaluation dashboard. So your script seems to work correctly (aside from the `baseline`-fetching block in your example that didn't run for me).

The high WIS values appears to be an issue with how `evalcast` fetches truth data for cumulative targets. `evalcast` sums cumulative signals over each week. So cumulative targets are being scored against values 7x higher than they should be.

As a workaround for now, you can call `evaluate_predictions` directly (`evaluate_covid_predictions` is a [thin wrapper](https://github.com/cmu-delphi/covidcast/blob/evalcast/R-packages/evalcast/R/evaluate_predictions.R#L121)) and provide your own truth data.

**Comment by nmdefries** [comment]
> COVIDhub_CDC-ensemble and COVIDhub-4_week_ensemble predictions match exactly

Yes, this is to be expected for some time periods.

The CDC ensemble is essentially pulling subsets of forecasts for specific targets from other `COVIDhub_*ensembles`, in a way that changed over time depending on what horizons and ensemble methods the CDC thought should be communicated. More information is available [on the Forecast Hub website](https://covid19forecasthub.org/doc/ensemble/).

**Comment by nmdefries** [comment]
We do intend to make a patch for the cumulative scoring issue you found, but I'm not sure of the timeline yet. In the meantime, I'd recommend taking a look at the workaround I mentioned above. The Reich lab's [`covidHubUtils` package](http://reichlab.io/covidHubUtils/articles/covidHubUtils-overview.html#working-with-scored-forecasts) also provides utilities for evaluating forecasts.

**Comment by zterner-mitre** [comment]
Thank you! This is all really helpful. I appreciate knowing that the WIS thing is indeed an issue, and also knowing that there are other functions (yours and the `covidHubUtils` package) which could be used to accomplish the same thing.
