### ISSUE TITLE
Aug 29th cases per 100K value missing

### ISSUE THREAD

**Issue by ercbk** [cmu-delphi/covidcast#67]
data_source = "indicator-combination"  
signal = "confirmed_7dav_incidence_prop"

I use Metro Areas, but looking at your map, it appears to missing for states and counties as well.

**Comment by krivard** [comment]
Thanks for the report -- it looks like one of the source signals, USAFacts,
is missing on 8/29, causing the gap. Working on a repair run now.

**Comment by ercbk** [comment]
Looks like you got it. Thx, krivard.
