### ISSUE TITLE
Python choropleth plots not legible at small sizes

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast#75]
Consider the following:

```python
import covidcast
from datetime import date
import matplotlib.pyplot as plt
data = covidcast.signal("fb-survey", "smoothed_hh_cmnty_cli",
                        date(2020, 9, 8), date(2020, 9, 8),
                        geo_type="state")
covidcast.plot_choropleth(data, figsize=(6, 4))
plt.title("% who know someone who is sick, Sept 8, 2020")
```

I get this:

![Screen Shot 2020-09-11 at 1 14 47 PM](https://user-images.githubusercontent.com/711629/92954050-c6d9ee00-f430-11ea-855c-f46b793ca651.png)

The colorbar is simply much too small for this size. I have to increase the figsize to at least `(12, 10)` to fit the colorbar text without collisions. Is it possible to adjust the colorbar drawing so it uses the available space more effectively? We could have it be full-width, but then large maps would look goofy.

**Comment by chinandrew** [comment]
How small do we think we need to go? With just changing arguments I can get it working down to `figsize=(6,4)` (but no smaller than that), with...not too much goofiness to the large maps


(6,4)
![Screenshot from 2020-09-11 13-40-57](https://user-images.githubusercontent.com/20176218/92971681-c7c14e80-f435-11ea-943d-129987961a38.png)


default (12.8,9.6)
![Screenshot from 2020-09-11 13-50-19](https://user-images.githubusercontent.com/20176218/92971676-c3953100-f435-11ea-9695-b868e681e55e.png)

**Comment by capnrefsmmat** [comment]
I guess `(6, 4)` is a reasonable minimum. Is there also an option to pick better ticks? For example, in the images you posted, it'd look a lot nicer if the scale just was 0 to 2 by 0.25 increments, instead of needing 3 decimal digits for each. In R, ggplot2 will try to find nice breaks if it can.

**Comment by chinandrew** [comment]
Right now the line breaks are 8 ticks between 0 and mean+3 std dev, which aligns with the R package. I could just make it round to 2 decimals, which is also what the R package does (I had left out since the large plots had enough space). Could also do equal intervals, maybe by rounding vmax to the nearest 0.25, though that has consequences if someone enters a custom vmax.

Then (6,4) looks like this
![Screenshot from 2020-09-11 16-37-49](https://user-images.githubusercontent.com/20176218/92981062-2d6d0500-f44d-11ea-8d01-d42829fbf507.png)

**Comment by capnrefsmmat** [comment]
I think that looks pretty good. 2 decimals should be fine for almost any case, and would in fact be overkill for many signals (do we need two decimals when comparing 55% to 60%?). But a fancier automatic scheme to pick breakpoints is out of scope here.

**Comment by chinandrew** [comment]
cool, Opened #81
