### ISSUE TITLE
Make predictions cards and score cards S3 objects with print and plot functions

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#98]
Currently they are tibbles, i.e. of class

`"tbl_df"     "tbl"        "data.frame"`.

Instead, we'd have them inherit from the above but be their own class.  For example, a predictions card would have class

`"predictions_card"     "tbl_df"     "tbl"        "data.frame"`

and then

* `print.predictions_card` would print out some of the attribute information (for example, name of the forecaster, `forecast_date`, `ahead`, etc.)
* `plot.predictions_card` would make the trajectory plots

Same idea for scorecards.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970448218457) by [Unito](https://www.unito.io/learn-more)

**Comment by jacobbien** [comment]
To clarify, `plot.predictions_card` would probably just call the function described here: #101.

**Comment by bnaras** [comment]
I can take this too.

**Comment by jacobbien** [comment]
Great!

**Comment by jacobbien** [comment]
Hi @bnaras!  I'm responding to the part of what you wrote in #150 that has to do with the S3 methods.  In my opinion, the main impetus for this would be the print method.  In particular, I find myself printing a list of predictions cards (which currently prints a list of tibbles) and then I want to know what the forecaster, ahead, and geo_type of these are.

For example, consider the following code:
```
forecast_dates <- evalcast::get_forecast_dates("CMU-TimeSeries")[1:4]
pc_cmu <- evalcast::get_covidhub_predictions("CMU-TimeSeries", forecast_dates)
```
This gives a list of 20 predictions cards, and printing `pc_cmu` gives me little information.  It'd be helpful if in addition to the tibble, I get to see something like
```
forecaster name: CMU-TimeSeries; ahead: 2; incidence_period: "epiweek"; geo_type: "state"; forecast_date: 2020-10-01
```
And for a score card, we'd like to know the as_of date.

**Comment by jacobbien** [comment]
I'm responding to the S3 aspect of this discussion in issue #98 just to keep things organized.

**Comment by jacobbien** [comment]
My understanding of what @dajmcdon suggests (and perhaps this is what @bnaras is suggesting as well?) is that it would be easier to work with one very long tibble rather than a list of tibbles that have attributes.  I'm open to this suggestion and had considered it a while ago.  I think one motivation for the separate tibbles with attributes is that I wanted to have all the metadata that would be needed to reproduce the run of that particular forecaster doing that particular forecast task.  I guess this addresses @bnaras 's question as well... a predictions card is not just the set of predictions that a forecaster makes in a particular situation but also all the meta information needed to reproduce that call.

@dajmcdon - I suppose it might be nice to have a function that performs the bind_rows and adds the identifiers needed to uniquely identify individual prediction tasks (forecast_date, ahead, incidence_period, geo_type, response).  This would make it easy for users to do what they like with it.  That function could also have a flag that allows the user to decide whether to unnest the forecast_distributions to make this more accessible to users who don't want to work with list-columns.  The reason the scorecards have the list-column is that the error measure is computed on a per-location basis and I didn't want to repeat that same error value 23 times for each location.

**Comment by ryantibs** [comment]
@jacobbien @dajmcdon @bnaras Just wanted to chime in here, RE one big tibble versus list of tibbles.

We have the same issue in the covidcast package with signals.  The return object of `covidcast_signal()` is a `covidcast_signal` data frame.  On a branch modeltools, I'm nearly done with `covidcast_signals()` which allows you to fetch multiple signals as once.  Decided to make the return object a list of `covidcast_signal` data frames, rather than one big data frame (tall or wide).  Then implemented an `aggregate_signals()` function which appropriately binds the rows (in tall format) or columns (in wide format), and in either case, preserve the metadata.  

So I think keeping predictions cards as a list makes sense structurally, and then you could have an `aggregate_cards()` function to aggregate predictions cards or score cards (if these were assigned S3 classes, then `aggregate_cards()` could operate detect the class and operate differently in the two cases, if you needed to have different considerations).

 you have multiple signals, then I decided to implement

**Comment by dajmcdon** [comment]
I think to @jacobbien 's point: there are lots of reasons to keep the cards as is (as are) for the sake of reproducibility. It also seems like (my personal experience) there are too many variables (aheads, forecasters, forecast_date, geo_values) to allow for anticipating the end user's goals re plotting/printing etc. So, on the prediction cards, I vote to make the "classes" help us aggregate when desired, by adding enough attributes. 

On the score card side, some of the methods already handle different "collections", see for example [Jacob's talk](https://github.com/cmu-delphi/covidcast/blob/main/docs/talks/evalcast/talk.Rmd). It would probably help to clean up that functionality by allowing the plot options to deal with multiple aheads or forecasters predictably (maybe a "card_catelog"??) to deal with lists of lists of cards.
