### ISSUE TITLE
Use Zoltar API rather than scraping GitHub

### ISSUE THREAD

**Issue by jacobbien** [cmu-delphi/covidcast#99]
The functions in evalcast's [get_covidhub_predictions.R](https://github.com/cmu-delphi/covidcast/blob/evalcast/R-packages/evalcast/R/get_covidhub_predictions.R) currently use `rvest` and `xml2` to scrape data off of github.

* Do this the proper way with the github API, accessible through the R package [`gh`](https://github.com/r-lib/gh).  This means rewriting `evalcast::get_forecast_dates` and `evalcast::get_covid_hub_forecaster_names`.

**EDIT: Apparently the [zoltr](http://reichlab.io/zoltr/) R package is intended for this.  So a starting point would be to look at that package.**

* When `evalcast::get_covidhub_predictions` retrieves a csv file from a forecaster for a given forecast date, the "as of" principle should apply, i.e., we should get the csv file that had been posted as of the forecast date.   Nick Reich noted that this is not always the case, as sometimes forecasters replace their file later.  I'm not sure how much this occurs, but this is certainly an important point for ensuring fairness.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198968030437421/1198970312009533) by [Unito](https://www.unito.io/learn-more)

**Comment by nickreich** [comment]
Note that we are likely to start supporting forecast versions in future versions of zoltar (maybe by end of 2020?) but as of right now, the [covid hub zoltar project](https://zoltardata.com/project/44) just stores whatever forecast was most recently submitted.

**Comment by nickreich** [comment]
relevant resource for using zoltr to get/plot forecasts: https://covid19forecasthub.org/talks/zoltar.html#(1)

**Comment by ryantibs** [comment]
@jacobbien @dajmcdon @bnaras @JedGrabman Just want to draw attention to the covidHubUtils package which Nick's group is working on.  We may be able to use this package directly for this, and just important the relevant functions directly into evalcast (which would save us re-implementing stuff).  

See this issue I just posted on their GitHub: https://github.com/reichlab/covidHubUtils/issues/20

**Comment by ryantibs** [comment]
@jacobbien @dajmcdon @bnaras Just an update that Nick implemented the ability for anybody to use covidHubUtils pkg to get forecasts from Zoltar (without needing an account), based on my request in reichlab/covidHubUtils#20.  So we should be good to go in plugging this into evalcast (redefining `get_covidhub_predictions()` to just use the relevant covidHubUtils functions).

**Comment by kateharwood** [comment]
@ryantibs @dajmcdon what is the rough priority of this now?

**Comment by dajmcdon** [comment]
I would say "toward the higher priority" end of the spectrum. I'll have a better idea when @JedGrabman recreates Ryan's notebook with the memoization.

**Comment by JedGrabman** [comment]
Ryan's notebook (#240) is now live on the main branch at [covidcast/R-notebooks/covidhub_evaluation.Rmd](https://github.com/cmu-delphi/covidcast/blob/f2794447a3778cb4bb5be4ea7c7f14474102c547/R-notebooks/covidhub_evaluation.Rmd) and memoization has been merged into the evalcast branch (#241). As expected, the memoization helps quite a bit if the same data has already been retrieved, but of course has no impact on the first call.

Perhaps the more relevant note is that the majority of time spent on `get_covidhub_predictions` happens during processing and not data retrieval (#280). This reduces any potential performance benefit we might see from using Zoltar, but the increased stability from using a dedicated API still makes addressing this issue worthwhile.
